import { describe, expect, it } from 'vitest';

import { validateMemoryTemplateContract } from '../../shared/parsing/memory-template-contract';

function buildValidMemory(overrides: { triggerBlock?: string; bodyTail?: string } = {}): string {
  return [
    '---',
    'title: "Memory Template Contract Proof"',
    'description: "Contract-proof memory fixture with required anchors and frontmatter."',
    overrides.triggerBlock ?? [
      'trigger_phrases:',
      '  - "memory template contract"',
      '  - "contract proof"',
    ].join('\n'),
    'importance_tier: "normal"',
    'contextType: "implementation"',
    '---',
    '',
    '# Memory Template Contract Proof',
    '',
    '## SESSION SUMMARY',
    '',
    '| **Meta Data** | **Value** |',
    '|:--------------|:----------|',
    '| Total Messages | 3 |',
    '',
    '<!-- ANCHOR:continue-session -->',
    '<a id="continue-session"></a>',
    '',
    '## CONTINUE SESSION',
    '',
    'Continue the implementation from the last verified checkpoint.',
    '',
    '<!-- ANCHOR:project-state-snapshot -->',
    '<a id="project-state-snapshot"></a>',
    '',
    '## PROJECT STATE SNAPSHOT',
    '',
    'All mandatory sections are present and correctly scaffolded.',
    '',
    '<!-- ANCHOR:decisions -->',
    '<a id="decisions"></a>',
    '',
    '## 2. DECISIONS',
    '',
    'A single contract validator is now the source of truth.',
    '',
    '<!-- ANCHOR:session-history -->',
    '<a id="conversation"></a>',
    '',
    '## 3. CONVERSATION',
    '',
    'User requested rigorous contract-based proof.',
    '',
    '<!-- ANCHOR:recovery-hints -->',
    '<a id="recovery-hints"></a>',
    '',
    '## RECOVERY HINTS',
    '',
    'Re-run the validator and creation-path tests if this changes again.',
    '',
    '<!-- ANCHOR:metadata -->',
    '<a id="memory-metadata"></a>',
    '',
    '## MEMORY METADATA',
    '',
    '```yaml',
    'session_id: "test-session"',
    '```',
    '',
    '<!-- /ANCHOR:metadata -->',
    overrides.bodyTail ?? '',
  ].join('\n');
}

describe('memory template contract validator', () => {
  it('accepts a structurally compliant memory', () => {
    const result = validateMemoryTemplateContract(buildValidMemory());

    expect(result.valid).toBe(true);
    expect(result.violations).toEqual([]);
  });

  it('rejects missing anchor/id scaffolding for mandatory sections', () => {
    const result = validateMemoryTemplateContract(
      buildValidMemory().replace('<!-- ANCHOR:project-state-snapshot -->\n', '')
    );

    expect(result.valid).toBe(false);
    expect(result.missingAnchors).toContain('project-state-snapshot');
  });

  it('rejects malformed trigger_phrases frontmatter shapes', () => {
    const result = validateMemoryTemplateContract(
      buildValidMemory({ triggerBlock: 'trigger_phrases: "session summary"' })
    );

    expect(result.valid).toBe(false);
    expect(result.violations.some((violation) => violation.code === 'invalid_trigger_phrases')).toBe(true);
  });

  it('rejects raw mustache leakage', () => {
    const result = validateMemoryTemplateContract(
      buildValidMemory({
        bodyTail: [
          '',
          '---',
          '',
          '---',
          '',
          '## TABLE OF CONTENTS',
          '',
          '- [CONTINUE SESSION](#continue-session)',
          '',
          '{{TRIGGER_PHRASES}}',
        ].join('\n'),
      })
    );

    expect(result.valid).toBe(false);
    expect(result.unexpectedTemplateArtifacts).toContain('raw_mustache_literal');
  });

  it('enforces conditional section scaffolding only when optional sections are present', () => {
    const result = validateMemoryTemplateContract([
      buildValidMemory(),
      '',
      '<a id="workflow-visualization"></a>',
      '',
      '## 4. WORKFLOW VISUALIZATION',
      '',
      'This optional section intentionally omits its ANCHOR comment.',
    ].join('\n'));

    expect(result.valid).toBe(false);
    expect(result.missingAnchors).toContain('workflow-visualization');
  });

  it('rejects missing blank line between frontmatter and body', () => {
    const noBlankLine = buildValidMemory().replace('---\n\n# Memory', '---\n# Memory');
    const result = validateMemoryTemplateContract(noBlankLine);

    expect(result.valid).toBe(false);
    expect(result.violations.some((v) => v.code === 'missing_blank_line_after_frontmatter')).toBe(true);
  });

  it('rejects orphaned closing metadata anchors outside the metadata section', () => {
    const result = validateMemoryTemplateContract([
      buildValidMemory(),
      '',
      '---',
      '',
      '*Generated by system-spec-kit skill v1.7.2*',
      '',
      '<!-- /ANCHOR:metadata -->',
    ].join('\n'));

    expect(result.valid).toBe(false);
    expect(
      result.violations.some(
        (violation) =>
          violation.code === 'missing_anchor_comment'
          && violation.message.includes('duplicate or orphaned closing ANCHOR comments')
      )
    ).toBe(true);
  });
});
