import yaml from "js-yaml";
import { parseGuardrails } from "@/utils/guardrails";
import type { Agent } from "@/components/agents/AgentForm";
import { cleanModelId, MODEL_ID_WARNING, safeIdentifier, safeTitle } from "./swarmExportTools";

export type ExportFormat =
  | "json"
  | "yaml"
  | "autogen"
  | "docker"
  | "langchain-py"
  | "langchain-ts"
  | "langgraph-py"
  | "langgraph-ts"
  | "strands-py"
  | "strands-ts";

/** A finite number in range, for values interpolated BARE into generated code. */
function safeNumber(v: unknown, fallback: number, min: number, max: number): number {
  if (v === null || v === undefined || v === "") return fallback;
  const n = typeof v === "number" ? v : Number(v);
  if (!Number.isFinite(n)) return fallback;
  return Math.min(max, Math.max(min, n));
}

export function buildAgentManifest(agent: Agent) {
  const tools = (agent.tools || {}) as any;
  // Tool ids are OBJECT KEYS FROM THE IMPORTED agent.json, so they are as
  // attacker-controlled as the model id was, and they reach generated
  // TypeScript unquoted: `description: "${t} — implement your logic here."`.
  // A key of `x"); process.exit(1); //` closes that literal. Every real id is
  // `kb_search`-shaped, so safeIdentifier is the identity function on all of
  // them and this costs nothing.
  const builtIn = Object.entries(tools.builtInTools || {})
    .filter(([, v]) => v)
    .map(([k]) => safeIdentifier(k, "tool"));
  const workflows = Object.entries(tools.activeWorkflows || {})
    .filter(([, v]) => v)
    .map(([k]) => safeIdentifier(k, "workflow"));

  return {
    schema: "agent.json/v1",
    name: agent.name,
    description: agent.description,
    system_prompt: agent.system_prompt,
    model: {
      // Numbers, not whatever is on the row. These are interpolated BARE into
      // generated Python and TypeScript — `temperature: ${...}` with no
      // quotes — so a non-numeric value is arbitrary code in the output.
      provider: safeIdentifier(agent.llm_provider, "openrouter"),
      model: safeIdentifier(agent.llm_model, "gpt-4o"),
      temperature: safeNumber(agent.temperature, 0.7, 0, 2),
      max_tokens: Math.round(safeNumber(agent.max_tokens, 4096, 1, 200_000)),
    },
    tools: {
      built_in: builtIn,
      workflows,
      requires_config: builtIn.filter((id) => tools.toolConfigs?.[id]),
    },
    guardrails: tools.guardrails || {},
    knowledge_base_id: agent.knowledge_base_id,
    exported_at: new Date().toISOString(),
  };
}

export function buildCrewAIYaml(agent: Agent): string {
  const manifest = buildAgentManifest(agent);
  const crewConfig = {
    agents: {
      [agent.name.toLowerCase().replace(/\s+/g, "_")]: {
        role: agent.name,
        goal: agent.description || "Assist the user effectively",
        backstory: agent.system_prompt || "An AI agent powered by AgentSwarm.",
        llm: `${manifest.model.provider}/${manifest.model.model}`,
        temperature: manifest.model.temperature,
        max_tokens: manifest.model.max_tokens,
        tools: manifest.tools.built_in,
        verbose: true,
        allow_delegation: false,
      },
    },
  };
  return yaml.dump(crewConfig, { lineWidth: 120 });
}

export function buildDockerfile(agent: Agent): string {
  const safeName = agent.name.toLowerCase().replace(/[^a-z0-9]/g, "-");
  return `# Dockerfile for ${safeTitle(agent.name)}
# Generated by AgentSwarm — https://agentswarms.fyi

FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir crewai langchain openai anthropic pyyaml

COPY agent.yaml /app/agent.yaml
COPY agent.json /app/agent.json
COPY run.py /app/run.py

ENV AGENT_NAME="${safeName}"
ENV LLM_PROVIDER="${safeIdentifier(agent.llm_provider, "openrouter")}"
ENV LLM_MODEL="${safeIdentifier(agent.llm_model, "gpt-4o")}"

# Set your API key at runtime:
# docker run -e OPENAI_API_KEY=... ${safeName}

EXPOSE 8080
CMD ["python", "run.py"]
`;
}

export function buildRunPy(agent: Agent): string {
  return `"""Standalone runner for ${safeTitle(agent.name)}"""
import os, json, yaml
from crewai import Agent, Task, Crew

with open("agent.yaml") as f:
    cfg = yaml.safe_load(f)

agent_key = list(cfg["agents"].keys())[0]
a = cfg["agents"][agent_key]

agent = Agent(
    role=a["role"],
    goal=a["goal"],
    backstory=a["backstory"],
    verbose=True,
)

if __name__ == "__main__":
    print(f"Agent {a['role']} ready. Provider: {os.getenv('LLM_PROVIDER')}")
`;
}

export function downloadFile(filename: string, content: string, mime = "text/plain") {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function buildAutoGenPython(agent: Agent): string {
  const manifest = buildAgentManifest(agent);
  const safeName = agent.name.replace(/[^A-Za-z0-9_]/g, "_");
  const systemMsg = JSON.stringify(
    agent.system_prompt || `You are ${agent.name}, ${agent.description || "a helpful AI agent"}.`,
  );
  const tools = manifest.tools.built_in;
  return `"""AutoGen agent definition for ${safeTitle(agent.name)}
Generated by AgentSwarm — https://agentswarms.fyi

!! ${MODEL_ID_WARNING}

Install:
    pip install pyautogen

Run:
    export OPENAI_API_KEY=sk-...
    python ${safeName}.py
"""
import os
from autogen import AssistantAgent, UserProxyAgent

llm_config = {
    "model": "${cleanModelId(manifest.model.model)}",
    "api_key": os.environ.get("OPENAI_API_KEY"),
    "temperature": ${manifest.model.temperature},
    "max_tokens": ${manifest.model.max_tokens},
}

${safeName} = AssistantAgent(
    name="${safeName}",
    system_message=${systemMsg},
    llm_config=llm_config,
)

user = UserProxyAgent(
    name="user",
    human_input_mode="ALWAYS",
    code_execution_config={"use_docker": False},
)

# Tools available to this agent (registered separately as needed):
# ${tools.length ? tools.join(", ") : "(none)"}

if __name__ == "__main__":
    user.initiate_chat(${safeName}, message="Hello!")
`;
}

/* ────────────────────────────────────────────────────────────────────────
   LangChain / LangGraph helpers
   ──────────────────────────────────────────────────────────────────────── */

/**
 * Detect the actual model family from either the explicit provider field OR
 * the model id itself. Gateway-routed models often carry a `google/…` or
 * `anthropic/…` prefix even when `llm_provider` is something neutral like
 * `openrouter` — without this, gemini/claude models get wrapped with
 * ChatOpenAI and the OpenAI SDK rejects them at runtime.
 */
function detectFamily(provider: string, model: string): "google" | "anthropic" | "openai" {
  const p = (provider || "").toLowerCase();
  const m = (model || "").toLowerCase();
  if (p.includes("anthropic") || m.startsWith("anthropic/") || m.startsWith("claude-"))
    return "anthropic";
  if (
    p.includes("google") ||
    p.includes("gemini") ||
    p.includes("vertex") ||
    m.startsWith("google/") ||
    m.startsWith("gemini-") ||
    m.includes("/gemini-")
  ) {
    return "google";
  }
  return "openai";
}

function pyModelClass(
  provider: string,
  model = "",
): { importLine: string; cls: string; envVar: string } {
  const fam = detectFamily(provider, model);
  if (fam === "anthropic")
    return {
      importLine: "from langchain_anthropic import ChatAnthropic",
      cls: "ChatAnthropic",
      envVar: "ANTHROPIC_API_KEY",
    };
  if (fam === "google")
    return {
      importLine: "from langchain_google_genai import ChatGoogleGenerativeAI",
      cls: "ChatGoogleGenerativeAI",
      envVar: "GOOGLE_API_KEY",
    };
  return {
    importLine: "from langchain_openai import ChatOpenAI",
    cls: "ChatOpenAI",
    envVar: "OPENAI_API_KEY",
  };
}

function tsModelClass(
  provider: string,
  model = "",
): { importLine: string; cls: string; envVar: string } {
  const fam = detectFamily(provider, model);
  if (fam === "anthropic")
    return {
      importLine: 'import { ChatAnthropic } from "@langchain/anthropic";',
      cls: "ChatAnthropic",
      envVar: "ANTHROPIC_API_KEY",
    };
  if (fam === "google")
    return {
      importLine: 'import { ChatGoogleGenerativeAI } from "@langchain/google-genai";',
      cls: "ChatGoogleGenerativeAI",
      envVar: "GOOGLE_API_KEY",
    };
  return {
    importLine: 'import { ChatOpenAI } from "@langchain/openai";',
    cls: "ChatOpenAI",
    envVar: "OPENAI_API_KEY",
  };
}

function pyToolStubs(tools: string[]): string {
  if (!tools.length) return "# No tools configured for this agent.\ntools: list = []\n";
  const stubs = tools.map((t) => {
    const fn = t.replace(/[^a-zA-Z0-9_]/g, "_");
    return `@tool\ndef ${fn}(query: str) -> str:\n    """${t} — implement your logic here."""\n    return f"${fn} result for: {query}"\n`;
  });
  return (
    stubs.join("\n") +
    `\ntools = [${tools.map((t) => t.replace(/[^a-zA-Z0-9_]/g, "_")).join(", ")}]\n`
  );
}

function tsToolStubs(tools: string[]): string {
  if (!tools.length)
    return "// No tools configured for this agent.\nconst tools: DynamicStructuredTool[] = [];\n";
  const stubs = tools.map((t) => {
    const fn = t.replace(/[^a-zA-Z0-9_]/g, "_");
    return `const ${fn}Tool = tool(\n  async ({ query }: { query: string }) => {\n    // TODO: implement ${t}\n    return \`${fn} result for: \${query}\`;\n  },\n  {\n    name: "${fn}",\n    description: "${t} — implement your logic here.",\n    schema: z.object({ query: z.string().describe("The input query") }),\n  }\n);\n`;
  });
  return (
    stubs.join("\n") +
    `\nconst tools = [${tools.map((t) => t.replace(/[^a-zA-Z0-9_]/g, "_") + "Tool").join(", ")}];\n`
  );
}

export function buildLangChainPython(agent: Agent): string {
  const manifest = buildAgentManifest(agent);
  const { importLine, cls, envVar } = pyModelClass(agent.llm_provider || "", agent.llm_model || "");
  const safeName = agent.name.replace(/[^A-Za-z0-9_]/g, "_");
  const systemMsg = JSON.stringify(agent.system_prompt || `You are ${agent.name}.`);
  const tools = manifest.tools.built_in;
  const modelId = cleanModelId(agent.llm_model || "");

  return `"""LangChain agent: ${safeTitle(agent.name)}
Generated by AgentSwarm — https://agentswarms.fyi

!! ${MODEL_ID_WARNING}

Install:
    pip install langchain-core langchain-openai langchain-anthropic langchain-google-genai

Run:
    export ${envVar}=...
    python ${safeName}_langchain.py
"""
import os
${importLine}
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.output_parsers import StrOutputParser
from langchain_core.tools import tool

# ── Model ──
model = ${cls}(
    model="${modelId}",
    temperature=${manifest.model.temperature},
    max_tokens=${manifest.model.max_tokens},
)

# ── Tools ──
${pyToolStubs(tools)}
# ── Prompt ──
prompt = ChatPromptTemplate.from_messages([
    ("system", ${systemMsg}),
    MessagesPlaceholder("chat_history", optional=True),
    ("human", "{input}"),
])

# ── Chain (LCEL) ──
${tools.length ? `model_with_tools = model.bind_tools(tools)\nchain = prompt | model_with_tools` : `chain = prompt | model | StrOutputParser()`}

if __name__ == "__main__":
    result = chain.invoke({"input": "Hello! What can you do?"})
    print(result${tools.length ? "" : ""})
`;
}

export function buildLangChainTypeScript(agent: Agent): string {
  const manifest = buildAgentManifest(agent);
  const { importLine, cls, envVar } = tsModelClass(agent.llm_provider || "", agent.llm_model || "");
  const safeName = agent.name.replace(/[^A-Za-z0-9_]/g, "_");
  const systemMsg = JSON.stringify(agent.system_prompt || `You are ${agent.name}.`);
  const tools = manifest.tools.built_in;
  const modelId = cleanModelId(agent.llm_model || "");

  return `/**
 * LangChain agent: ${safeTitle(agent.name)}
 * Generated by AgentSwarm — https://agentswarms.fyi
 *
 * !! ${MODEL_ID_WARNING}
 *
 * Install:
 *   npm install @langchain/core @langchain/openai @langchain/anthropic @langchain/google-genai zod
 *
 * Run:
 *   export ${envVar}=...
 *   npx tsx ${safeName}_langchain.ts
 */
${importLine}
import { ChatPromptTemplate, MessagesPlaceholder } from "@langchain/core/prompts";
import { StringOutputParser } from "@langchain/core/output_parsers";
import { DynamicStructuredTool, tool } from "@langchain/core/tools";
import { z } from "zod";

// ── Model ──
const model = new ${cls}({
  model: "${modelId}",
  temperature: ${manifest.model.temperature},
  maxTokens: ${manifest.model.max_tokens},
});

// ── Tools ──
${tsToolStubs(tools)}
// ── Prompt ──
const prompt = ChatPromptTemplate.fromMessages([
  ["system", ${systemMsg}],
  new MessagesPlaceholder({ variableName: "chat_history", optional: true }),
  ["human", "{input}"],
]);

// ── Chain (LCEL) ──
${tools.length ? `const modelWithTools = model.bindTools(tools);\nconst chain = prompt.pipe(modelWithTools);` : `const chain = prompt.pipe(model).pipe(new StringOutputParser());`}

async function main() {
  const result = await chain.invoke({ input: "Hello! What can you do?" });
  console.log(result);
}

main();
`;
}

export function buildLangGraphPythonSingle(agent: Agent): string {
  const manifest = buildAgentManifest(agent);
  const { importLine, cls, envVar } = pyModelClass(agent.llm_provider || "", agent.llm_model || "");
  const safeName = agent.name.replace(/[^A-Za-z0-9_]/g, "_");
  const systemMsg = JSON.stringify(agent.system_prompt || `You are ${agent.name}.`);
  const tools = manifest.tools.built_in;
  const modelId = cleanModelId(agent.llm_model || "");

  return `"""LangGraph ReAct agent: ${safeTitle(agent.name)}
Generated by AgentSwarm — https://agentswarms.fyi

!! ${MODEL_ID_WARNING}

Install:
    pip install langgraph langchain-core langchain-openai langchain-anthropic langchain-google-genai

Run:
    export ${envVar}=...
    python ${safeName}_langgraph.py
"""
import os
from typing import Annotated, TypedDict
${importLine}
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.tools import tool
from langgraph.graph import StateGraph, MessagesState, START, END
from langgraph.prebuilt import ToolNode

# ── Model ──
model = ${cls}(
    model="${modelId}",
    temperature=${manifest.model.temperature},
    max_tokens=${manifest.model.max_tokens},
)

# ── Tools ──
${pyToolStubs(tools)}
${tools.length ? `model_with_tools = model.bind_tools(tools)\ntool_node = ToolNode(tools)` : ""}

# ── Graph nodes ──
def agent_node(state: MessagesState) -> MessagesState:
    system = SystemMessage(content=${systemMsg})
    messages = [system] + state["messages"]
    response = ${tools.length ? "model_with_tools" : "model"}.invoke(messages)
    return {"messages": [response]}

def should_continue(state: MessagesState) -> str:
    last = state["messages"][-1]
    if hasattr(last, "tool_calls") and last.tool_calls:
        return "tools"
    return END

# ── Build graph ──
graph = StateGraph(MessagesState)
graph.add_node("agent", agent_node)
${tools.length ? `graph.add_node("tools", tool_node)` : ""}
graph.add_edge(START, "agent")
${tools.length ? `graph.add_conditional_edges("agent", should_continue, {"tools": "tools", END: END})\ngraph.add_edge("tools", "agent")` : `graph.add_edge("agent", END)`}

app = graph.compile()

if __name__ == "__main__":
    result = app.invoke({"messages": [HumanMessage(content="Hello! What can you do?")]})
    for msg in result["messages"]:
        print(f"{msg.type}: {msg.content}")
`;
}

export function buildLangGraphTypeScriptSingle(agent: Agent): string {
  const manifest = buildAgentManifest(agent);
  const { importLine, cls, envVar } = tsModelClass(agent.llm_provider || "", agent.llm_model || "");
  const safeName = agent.name.replace(/[^A-Za-z0-9_]/g, "_");
  const systemMsg = JSON.stringify(agent.system_prompt || `You are ${agent.name}.`);
  const tools = manifest.tools.built_in;
  const modelId = cleanModelId(agent.llm_model || "");

  return `/**
 * LangGraph ReAct agent: ${safeTitle(agent.name)}
 * Generated by AgentSwarm — https://agentswarms.fyi
 *
 * !! ${MODEL_ID_WARNING}
 *
 * Install:
 *   npm install @langchain/langgraph @langchain/core @langchain/openai @langchain/anthropic @langchain/google-genai zod
 *
 * Run:
 *   export ${envVar}=...
 *   npx tsx ${safeName}_langgraph.ts
 */
${importLine}
import { HumanMessage, SystemMessage, type BaseMessage } from "@langchain/core/messages";
import { DynamicStructuredTool, tool } from "@langchain/core/tools";
import { StateGraph, MessagesAnnotation, START, END } from "@langchain/langgraph";
import { ToolNode } from "@langchain/langgraph/prebuilt";
import { z } from "zod";

// ── Model ──
const model = new ${cls}({
  model: "${modelId}",
  temperature: ${manifest.model.temperature},
  maxTokens: ${manifest.model.max_tokens},
});

// ── Tools ──
${tsToolStubs(tools)}
${tools.length ? `const modelWithTools = model.bindTools(tools);\nconst toolNode = new ToolNode(tools);` : ""}

// ── Graph nodes ──
async function agentNode(state: typeof MessagesAnnotation.State) {
  const system = new SystemMessage(${systemMsg});
  const response = await ${tools.length ? "modelWithTools" : "model"}.invoke([system, ...state.messages]);
  return { messages: [response] };
}

function shouldContinue(state: typeof MessagesAnnotation.State): "tools" | "__end__" {
  const last = state.messages[state.messages.length - 1];
  if ("tool_calls" in last && (last as any).tool_calls?.length) {
    return "tools";
  }
  return "__end__";
}

// ── Build graph ──
const graph = new StateGraph(MessagesAnnotation)
  .addNode("agent", agentNode)${tools.length ? `\n  .addNode("tools", toolNode)` : ""}
  .addEdge(START, "agent")${tools.length ? `\n  .addConditionalEdges("agent", shouldContinue, { tools: "tools", __end__: END })\n  .addEdge("tools", "agent")` : `\n  .addEdge("agent", END)`}
  .compile();

async function main() {
  const result = await graph.invoke({
    messages: [new HumanMessage("Hello! What can you do?")],
  });
  for (const msg of result.messages) {
    console.log(\`\${msg._getType()}: \${msg.content}\`);
  }
}

main();
`;
}

/* ────────────────────────────────────────────────────────────────────────
   Strands Agents SDK (https://strandsagents.com) — single agent
   ──────────────────────────────────────────────────────────────────────── */

function strandsPyModel(
  provider: string,
  model: string,
  temperature: number,
): { importLine: string; expr: string } {
  const fam = detectFamily(provider, model);
  const id = cleanModelId(model);
  if (fam === "anthropic")
    return {
      importLine: "from strands.models.anthropic import AnthropicModel",
      expr: `AnthropicModel(client_args={"api_key": os.environ.get("ANTHROPIC_API_KEY")}, model_id="${id}", max_tokens=4096, params={"temperature": ${temperature}})`,
    };
  if (fam === "google")
    return {
      importLine: "from strands.models.gemini import GeminiModel",
      expr: `GeminiModel(client_args={"api_key": os.environ.get("GEMINI_API_KEY")}, model_id="${id}", params={"temperature": ${temperature}})`,
    };
  return {
    importLine: "from strands.models.openai import OpenAIModel",
    expr: `OpenAIModel(client_args={"api_key": os.environ.get("OPENAI_API_KEY")}, model_id="${id}", params={"temperature": ${temperature}})`,
  };
}

function strandsTsModel(
  provider: string,
  model: string,
  temperature: number,
): { importLine: string; expr: string } {
  const fam = detectFamily(provider, model);
  const id = cleanModelId(model);
  if (fam === "anthropic")
    return {
      importLine: 'import { AnthropicModel } from "@strands-agents/sdk/models/anthropic";',
      expr: `new AnthropicModel({ apiKey: process.env.ANTHROPIC_API_KEY, modelId: "${id}", maxTokens: 4096, params: { temperature: ${temperature} } })`,
    };
  if (fam === "google")
    return {
      importLine: 'import { GoogleModel } from "@strands-agents/sdk/models/google";',
      expr: `new GoogleModel({ apiKey: process.env.GEMINI_API_KEY, modelId: "${id}", params: { temperature: ${temperature} } })`,
    };
  return {
    importLine: 'import { OpenAIModel } from "@strands-agents/sdk/models/openai";',
    expr: `new OpenAIModel({ api: "chat", apiKey: process.env.OPENAI_API_KEY, modelId: "${id}", temperature: ${temperature} })`,
  };
}

export function buildStrandsPythonSingle(agent: Agent): string {
  const manifest = buildAgentManifest(agent);
  const safeName = agent.name.replace(/[^A-Za-z0-9_]/g, "_");
  const systemMsg = JSON.stringify(agent.system_prompt || `You are ${agent.name}.`);
  const tools = manifest.tools.built_in;
  const { importLine, expr } = strandsPyModel(
    agent.llm_provider || "",
    agent.llm_model || "",
    manifest.model.temperature,
  );

  const toolStubs = tools
    .map((t) => {
      const fn = t.replace(/[^a-zA-Z0-9_]/g, "_");
      return `@tool\ndef ${fn}(query: str) -> str:\n    """${t} — implement your logic here (hosted tools are not portable)."""\n    return f"TODO: implement ${fn} for: {query}"\n`;
    })
    .join("\n");

  return `"""Strands agent: ${safeTitle(agent.name)}
Generated by AgentSwarm — https://agentswarms.fyi

!! ${MODEL_ID_WARNING}

Fidelity note — this scaffold is a runnable STARTER, not a 1:1 copy of the hosted run:
  • Tool bodies are stubs (the platform's hosted tools are not portable).
  • Knowledge-base / RAG retrieval is NOT wired — attach your own retriever.
  • Guardrails and memory settings are not reproduced here.

Install:
    pip install strands-agents strands-agents-tools

Run:
    export ${detectFamily(agent.llm_provider || "", agent.llm_model || "") === "anthropic" ? "ANTHROPIC_API_KEY" : detectFamily(agent.llm_provider || "", agent.llm_model || "") === "google" ? "GEMINI_API_KEY" : "OPENAI_API_KEY"}=...
    python ${safeName}_strands.py
"""
import os
from strands import Agent${tools.length ? ", tool" : ""}
${importLine}

# ── Model ──
model = ${expr}

${tools.length ? `# ── Tools (stubs — implement each body) ──\n${toolStubs}\n` : ""}# ── Agent ──
agent = Agent(
    model=model,
    system_prompt=${systemMsg},${tools.length ? `\n    tools=[${tools.map((t) => t.replace(/[^a-zA-Z0-9_]/g, "_")).join(", ")}],` : ""}
)

if __name__ == "__main__":
    result = agent("Hello! What can you do?")
    print(result)
`;
}

export function buildStrandsTypeScriptSingle(agent: Agent): string {
  const manifest = buildAgentManifest(agent);
  const safeName = agent.name.replace(/[^A-Za-z0-9_]/g, "_");
  const systemMsg = JSON.stringify(agent.system_prompt || `You are ${agent.name}.`);
  const tools = manifest.tools.built_in;
  const { importLine, expr } = strandsTsModel(
    agent.llm_provider || "",
    agent.llm_model || "",
    manifest.model.temperature,
  );

  const toolStubs = tools
    .map((t) => {
      const fn = t.replace(/[^a-zA-Z0-9_]/g, "_");
      return `const ${fn} = tool({\n  name: ${JSON.stringify(t)},\n  description: "${t} — implement your logic here (hosted tools are not portable).",\n  inputSchema: z.object({ query: z.string().describe("The input query") }),\n  callback: (input) => {\n    // TODO: implement ${fn}\n    return \`TODO: implement ${fn} for: \${input.query}\`;\n  },\n});\n`;
    })
    .join("\n");

  const envVar =
    detectFamily(agent.llm_provider || "", agent.llm_model || "") === "anthropic"
      ? "ANTHROPIC_API_KEY"
      : detectFamily(agent.llm_provider || "", agent.llm_model || "") === "google"
        ? "GEMINI_API_KEY"
        : "OPENAI_API_KEY";

  return `/**
 * Strands agent: ${safeTitle(agent.name)}
 * Generated by AgentSwarm — https://agentswarms.fyi
 *
 * !! ${MODEL_ID_WARNING}
 *
 * Fidelity note — runnable STARTER, not a 1:1 copy of the hosted run:
 *   • Tool bodies are stubs (the platform's hosted tools are not portable).
 *   • Knowledge-base / RAG retrieval is NOT wired — attach your own retriever.
 *   • Guardrails and memory settings are not reproduced here.
 *
 * Install:
 *   npm install @strands-agents/sdk${tools.length ? " zod" : ""}
 *
 * Run:
 *   export ${envVar}=...
 *   npx tsx ${safeName}_strands.ts
 */
import { Agent${tools.length ? ", tool" : ""} } from "@strands-agents/sdk";
${importLine}${tools.length ? '\nimport z from "zod";' : ""}

${tools.length ? `// ── Tools (stubs — implement each body) ──\n${toolStubs}\n` : ""}// ── Agent ──
const agent = new Agent({
  model: ${expr},
  systemPrompt: ${systemMsg},${tools.length ? `\n  tools: [${tools.map((t) => t.replace(/[^a-zA-Z0-9_]/g, "_")).join(", ")}],` : ""}
  printer: false,
});

// Pull plain text out of an invoke() result regardless of message shape.
function asText(result: any): string {
  const m = result?.lastMessage;
  if (typeof m === "string") return m;
  if (Array.isArray(m?.content)) return m.content.map((b: any) => b?.text ?? "").join("");
  if (typeof m?.content === "string") return m.content;
  return m == null ? "" : JSON.stringify(m);
}

async function main() {
  const result = await agent.invoke("Hello! What can you do?");
  console.log(asText(result));
}

main();
`;
}

export function exportAgent(agent: Agent, format: ExportFormat) {
  const safeName = agent.name.toLowerCase().replace(/[^a-z0-9]/g, "-");
  if (format === "json") {
    downloadFile(
      `${safeName}.agent.json`,
      JSON.stringify(buildAgentManifest(agent), null, 2),
      "application/json",
    );
  } else if (format === "yaml") {
    downloadFile(`${safeName}.crewai.yaml`, buildCrewAIYaml(agent), "text/yaml");
  } else if (format === "autogen") {
    downloadFile(`${safeName}.autogen.py`, buildAutoGenPython(agent), "text/x-python");
  } else if (format === "langchain-py") {
    downloadFile(`${safeName}_langchain.py`, buildLangChainPython(agent), "text/x-python");
  } else if (format === "langchain-ts") {
    downloadFile(`${safeName}_langchain.ts`, buildLangChainTypeScript(agent), "text/typescript");
  } else if (format === "langgraph-py") {
    downloadFile(`${safeName}_langgraph.py`, buildLangGraphPythonSingle(agent), "text/x-python");
  } else if (format === "langgraph-ts") {
    downloadFile(
      `${safeName}_langgraph.ts`,
      buildLangGraphTypeScriptSingle(agent),
      "text/typescript",
    );
  } else if (format === "strands-py") {
    downloadFile(`${safeName}_strands.py`, buildStrandsPythonSingle(agent), "text/x-python");
  } else if (format === "strands-ts") {
    downloadFile(`${safeName}_strands.ts`, buildStrandsTypeScriptSingle(agent), "text/typescript");
  } else {
    const bundle = `=== Dockerfile ===\n${buildDockerfile(agent)}\n\n=== agent.yaml ===\n${buildCrewAIYaml(agent)}\n\n=== agent.json ===\n${JSON.stringify(buildAgentManifest(agent), null, 2)}\n\n=== run.py ===\n${buildRunPy(agent)}\n`;
    downloadFile(`${safeName}-docker-bundle.txt`, bundle, "text/plain");
  }
}

// ── Import validation ───────────────────────────────────────────────────────
//
// AN IMPORTED AGENT FILE IS UNTRUSTED INPUT. It arrives by drag-and-drop from
// wherever the user got it — a colleague, a gist, a vendor. Every field below
// used to be taken at face value and written straight to the database:
// `temperature: "hot"`, `max_tokens: 100000000` and a `name` that is an object
// all imported cleanly. max_tokens is the sharp one, because it is sent to the
// provider and drives spend directly.

/** A string, or the fallback. Rejects objects and arrays, and caps length. */
function str(v: unknown, fallback: string, max = 4000): string {
  return typeof v === "string" && v.trim() ? v.slice(0, max) : fallback;
}

/** An optional string — undefined rather than a fallback when absent. */
function optStr(v: unknown, max = 8000): string | undefined {
  return typeof v === "string" && v.trim() ? v.slice(0, max) : undefined;
}

/**
 * A finite number inside [min, max], or the fallback. Rejects "hot" and NaN.
 *
 * `null` and `undefined` are ABSENT, not zero. `Number(null)` is 0 and 0 is
 * finite, so a bare coercion turned `"temperature": null` — which means "I did
 * not set this" — into a fully deterministic 0 rather than the default. That
 * exact coercion has now caused three separate bugs in this codebase: alert
 * thresholds counting blank cells as zero, the PII phone detector, and this.
 */
function num(v: unknown, fallback: number, min: number, max: number): number {
  if (v === null || v === undefined || v === "") return fallback;
  const n = typeof v === "number" ? v : Number(v);
  if (!Number.isFinite(n)) return fallback;
  return Math.min(max, Math.max(min, n));
}

/** Built-in tool names: strings only, deduped, capped. */
function toolFlags(v: unknown): { flags: Record<string, boolean>; count: number } {
  // `built_in` was assumed to be an array — a string threw
  // "builtIn.map is not a function" out of the parser instead of being
  // reported as a malformed file.
  const names = Array.isArray(v) ? v.filter((t): t is string => typeof t === "string") : [];
  const unique = [...new Set(names)].slice(0, 64);
  return { flags: Object.fromEntries(unique.map((t) => [t, true])), count: unique.length };
}

/** Largest max_tokens an imported file may request. */
export const MAX_IMPORT_TOKENS = 200_000;

/** Largest agent file we will read. */
export const MAX_IMPORT_BYTES = 512 * 1024;

export function parseImportedAgent(
  content: string,
  filename: string,
): {
  name: string;
  description?: string;
  system_prompt?: string;
  llm_provider?: string;
  llm_model?: string;
  temperature?: number;
  max_tokens?: number;
  tools?: any;
  toolCount: number;
} {
  if (content.length > MAX_IMPORT_BYTES) {
    throw new Error(
      `File is too large (${Math.round(content.length / 1024)} KB). Agent files are a few KB; the limit is ${MAX_IMPORT_BYTES / 1024} KB.`,
    );
  }

  const isYaml = filename.endsWith(".yaml") || filename.endsWith(".yml");
  let parsed: any;
  if (isYaml) {
    // js-yaml v4 `load` uses the default schema, which cannot construct
    // functions or arbitrary types — checked, `!!js/function` is rejected.
    parsed = yaml.load(content);
    if (parsed?.agents && typeof parsed.agents === "object") {
      const key = Object.keys(parsed.agents)[0];
      const a = parsed.agents[key];
      if (!a || typeof a !== "object") throw new Error("No agent definition found in this file.");
      const llm = str(a.llm, "openrouter/openai/gpt-4o-mini", 200);
      const [provider, ...modelParts] = llm.split("/");
      const { flags, count } = toolFlags(a.tools);
      return {
        name: str(a.role, str(key, "Imported Agent", 200), 200),
        description: optStr(a.goal),
        system_prompt: optStr(a.backstory),
        llm_provider: str(provider, "openrouter", 60),
        llm_model: str(modelParts.join("/"), "openai/gpt-4o-mini", 200),
        temperature: num(a.temperature, 0.7, 0, 2),
        max_tokens: Math.round(num(a.max_tokens, 4096, 1, MAX_IMPORT_TOKENS)),
        tools: { builtInTools: flags },
        toolCount: count,
      };
    }
  } else {
    parsed = JSON.parse(content);
  }
  if (!parsed || typeof parsed !== "object") {
    throw new Error("This file does not contain an agent definition.");
  }
  const model = parsed.model && typeof parsed.model === "object" ? parsed.model : {};
  const { flags, count } = toolFlags(parsed.tools?.built_in);
  return {
    name: str(parsed.name, "Imported Agent", 200),
    description: optStr(parsed.description),
    system_prompt: optStr(parsed.system_prompt),
    llm_provider: str(model.provider, "openrouter", 60),
    llm_model: str(model.model, "google/gemini-3-flash-preview", 200),
    temperature: num(model.temperature, 0.7, 0, 2),
    max_tokens: Math.round(num(model.max_tokens, 4096, 1, MAX_IMPORT_TOKENS)),
    tools: {
      builtInTools: flags,
      // Normalised through the same parser the enforcer uses, so an imported
      // file cannot plant a guardrail shape the rest of the app will not
      // recognise — and cannot smuggle in a catastrophic `blockedPatterns`
      // regex, which was a remote DoS by e-mailed agent file before
      // looksCatastrophic existed.
      guardrails: parseGuardrails(parsed.guardrails),
    },
    toolCount: count,
  };
}
