/**
 * Convert a PortableSwarm graph into runnable LangGraph code (Python or TypeScript).
 *
 * Generated by AgentSwarm — https://agentswarms.fyi
 */
import type { PortableSwarm, PortableSwarmNode, PortableSwarmEdge } from "./swarmPortable";
import { downloadFile } from "./agentExport";
import { cleanModelId, toolDescription, MODEL_ID_WARNING, FIDELITY_NOTE } from "./swarmExportTools";

/* ────────────────────────────────────────────────────────────────────────
   Helpers
   ──────────────────────────────────────────────────────────────────────── */

function safePy(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^(\d)/, "_$1") || "node";
}

function safeTs(name: string): string {
  return safePy(name);
}

/**
 * Graph node + function names are derived from `safePy(label || id)`. Two nodes
 * sharing a label (e.g. two "Researcher" agents, or emoji-only labels that both
 * collapse to "node") would emit duplicate `def …_node` definitions AND a
 * duplicate `add_node` → LangGraph raises a duplicate-node error at compile.
 *
 * We disambiguate up front by rewriting *only colliding* labels to a unique,
 * already-safe value (e.g. "Researcher_2"). Edges reference node ids (untouched),
 * so the topology is preserved — only the generated identifiers change.
 */
function disambiguateLabels(nodes: PortableSwarmNode[]): PortableSwarmNode[] {
  const used = new Set<string>();
  return nodes.map((n) => {
    const base = safePy(n.label || n.id) || "node";
    let key = base;
    let i = 2;
    while (used.has(key)) key = `${base}_${i++}`;
    used.add(key);
    // safePy(key) === key (key is already safe), so setting label = key makes
    // every downstream safePy(label) call produce this unique identifier.
    return key === base ? n : { ...n, label: key };
  });
}

/**
 * Detect the actual model family from either the explicit provider field OR
 * the model string itself (which often carries a `google/`, `openai/`,
 * `anthropic/` prefix from AgentSwarms' gateway routing).
 */
function detectFamily(provider?: string, model?: string): "google" | "anthropic" | "openai" {
  const p = (provider || "").toLowerCase();
  const m = (model || "").toLowerCase();
  if (p.includes("anthropic") || m.startsWith("anthropic/") || m.startsWith("claude-"))
    return "anthropic";
  if (
    p.includes("google") ||
    p.includes("gemini") ||
    p.includes("vertex") ||
    m.startsWith("google/") ||
    m.startsWith("gemini-") ||
    m.includes("/gemini-")
  ) {
    return "google";
  }
  return "openai";
}

function pyModelImport(family: "google" | "anthropic" | "openai"): {
  importLine: string;
  cls: string;
} {
  if (family === "anthropic")
    return { importLine: "from langchain_anthropic import ChatAnthropic", cls: "ChatAnthropic" };
  if (family === "google")
    return {
      importLine: "from langchain_google_genai import ChatGoogleGenerativeAI",
      cls: "ChatGoogleGenerativeAI",
    };
  return { importLine: "from langchain_openai import ChatOpenAI", cls: "ChatOpenAI" };
}

function tsModelImport(family: "google" | "anthropic" | "openai"): {
  importLine: string;
  cls: string;
} {
  if (family === "anthropic")
    return {
      importLine: 'import { ChatAnthropic } from "@langchain/anthropic";',
      cls: "ChatAnthropic",
    };
  if (family === "google")
    return {
      importLine: 'import { ChatGoogleGenerativeAI } from "@langchain/google-genai";',
      cls: "ChatGoogleGenerativeAI",
    };
  return { importLine: 'import { ChatOpenAI } from "@langchain/openai";', cls: "ChatOpenAI" };
}

type NodesByKind = Record<string, PortableSwarmNode[]>;

function groupByKind(nodes: PortableSwarmNode[]): NodesByKind {
  const map: NodesByKind = {};
  for (const n of nodes) {
    (map[n.kind] ??= []).push(n);
  }
  return map;
}

function outEdges(nodeId: string, edges: PortableSwarmEdge[]): PortableSwarmEdge[] {
  return edges.filter((e) => e.source === nodeId);
}

/** Unique, ordered list of tool ids enabled across all agent nodes. */
function collectTools(agentNodes: PortableSwarmNode[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const a of agentNodes) {
    for (const t of a.enabledTools || []) {
      if (!seen.has(t)) {
        seen.add(t);
        out.push(t);
      }
    }
  }
  return out;
}

/** Collect outputVars of every node that feeds (directly) into `nodeId`. */
function upstreamOutputVars(
  nodeId: string,
  nodes: PortableSwarmNode[],
  edges: PortableSwarmEdge[],
): Array<{ label: string; outputVar: string }> {
  const result: Array<{ label: string; outputVar: string }> = [];
  for (const e of edges) {
    if (e.target !== nodeId) continue;
    const src = nodes.find((n) => n.id === e.source);
    if (!src || !src.outputVar) continue;
    result.push({ label: src.label || src.id, outputVar: src.outputVar });
  }
  return result;
}

/* ────────────────────────────────────────────────────────────────────────
   Python generator
   ──────────────────────────────────────────────────────────────────────── */

export function buildLangGraphPythonSwarm(swarm: PortableSwarm): string {
  const { edges } = swarm;
  const nodes = disambiguateLabels(swarm.nodes);
  const byKind = groupByKind(nodes);
  const agentNodes = byKind["agent"] || [];
  const conditionNodes = byKind["condition"] || [];
  const approvalNodes = byKind["approval"] || [];
  const loopNodes = byKind["loop"] || [];
  const inputNodes = byKind["input"] || [];
  const outputNodes = byKind["output"] || [];
  // Previously-ignored kinds. Without these, any edge to/from them referenced
  // a graph node that was never added → LangGraph compile error. We emit
  // runnable passthrough stubs so the graph compiles and the topology is
  // preserved; the bodies carry the original config as TODO comments.
  const evaluateNodes = byKind["evaluate"] || [];
  const functionNodes = byKind["function"] || [];
  const a2aNodes = byKind["a2a_remote"] || [];
  const otherNodes = [...evaluateNodes, ...functionNodes, ...a2aNodes];

  const inputIds = new Set(inputNodes.map((n) => n.id));
  const outputIds = new Set(outputNodes.map((n) => n.id));
  const conditionIds = new Set(conditionNodes.map((c) => c.id));

  const tools = collectTools(agentNodes);
  const anyTools = tools.length > 0;

  // Collect unique model imports (deduped by family)
  const modelImports = new Map<string, { importLine: string; cls: string }>();
  for (const a of agentNodes) {
    const fam = detectFamily(a.provider, a.model);
    const mi = pyModelImport(fam);
    modelImports.set(mi.cls, mi);
  }
  if (!modelImports.size) modelImports.set("ChatOpenAI", pyModelImport("openai"));

  const lines: string[] = [];
  lines.push(`"""LangGraph swarm: ${swarm.name}`);
  lines.push(`Generated by AgentSwarm — https://agentswarms.fyi`);
  lines.push(``);
  for (const n of FIDELITY_NOTE) lines.push(n);
  lines.push(``);
  lines.push(`!! ${MODEL_ID_WARNING}`);
  lines.push(``);
  lines.push(`Install:`);
  lines.push(
    `    pip install langgraph langchain-core langchain-openai langchain-anthropic langchain-google-genai`,
  );
  lines.push(``);
  lines.push(`Run:`);
  lines.push(`    # Set the API key(s) matching your model providers, e.g.:`);
  lines.push(`    #   export OPENAI_API_KEY=...`);
  lines.push(`    #   export ANTHROPIC_API_KEY=...`);
  lines.push(`    #   export GOOGLE_API_KEY=...`);
  lines.push(`    python ${safePy(swarm.name)}_langgraph.py`);
  lines.push(`"""`);
  lines.push(`import os`);
  lines.push(`from typing import TypedDict, Annotated`);
  lines.push(`from operator import add`);
  for (const mi of modelImports.values()) lines.push(mi.importLine);
  lines.push(`from langchain_core.messages import HumanMessage, SystemMessage, BaseMessage`);
  if (anyTools) lines.push(`from langchain_core.tools import tool`);
  lines.push(`from langgraph.graph import StateGraph, START, END`);
  if (approvalNodes.length) {
    lines.push(`from langgraph.types import interrupt`);
    // interrupt() only works when the graph is compiled with a checkpointer.
    lines.push(`from langgraph.checkpoint.memory import MemorySaver`);
  }
  if (a2aNodes.length) lines.push(`import json, urllib.request`);
  lines.push(``);

  // State — dedupe keys; never re-emit `messages` or `input`
  lines.push(`# ── State ──`);
  lines.push(`class SwarmState(TypedDict):`);
  lines.push(`    messages: Annotated[list[BaseMessage], add]`);
  lines.push(`    input: str`);
  const reserved = new Set(["messages", "input"]);
  const outputVars = new Set<string>();
  for (const n of nodes) {
    if (!n.outputVar) continue;
    const safe = safePy(n.outputVar);
    if (reserved.has(safe)) continue;
    outputVars.add(safe);
  }
  for (const v of outputVars) lines.push(`    ${v}: str`);
  lines.push(``);

  // Tool stubs (shared across agents that enable them)
  if (anyTools) {
    lines.push(`# ── Tools (stubs — implement each body; hosted tools are not portable) ──`);
    for (const t of tools) {
      const fn = safePy(t);
      lines.push(`@tool`);
      lines.push(`def ${fn}(query: str) -> str:`);
      lines.push(`    """${toolDescription(t)}"""`);
      lines.push(`    return f"TODO: implement ${fn} for: {query}"`);
      lines.push(``);
    }
  }

  // Model instances
  lines.push(`# ── Models ──`);
  for (const a of agentNodes) {
    const fam = detectFamily(a.provider, a.model);
    const mi = pyModelImport(fam);
    const varName = `model_${safePy(a.id)}`;
    lines.push(
      `${varName} = ${mi.cls}(model="${cleanModelId(a.model)}", temperature=${a.temperature ?? 0.7})`,
    );
  }
  lines.push(``);

  // Agent nodes — inject upstream outputs into the prompt
  lines.push(`# ── Agent nodes ──`);
  for (const a of agentNodes) {
    const fn = safePy(a.label || a.id);
    const sysMsg = JSON.stringify(a.systemPrompt || `You are ${a.label}.`);
    const outVar = a.outputVar ? safePy(a.outputVar) : null;
    const ups = upstreamOutputVars(a.id, nodes, edges).filter((u) => !inputIds.has(u.outputVar));
    const agentTools = (a.enabledTools || []).map((t) => safePy(t));

    lines.push(`def ${fn}_node(state: SwarmState) -> dict:`);
    lines.push(`    system = SystemMessage(content=${sysMsg})`);
    lines.push(
      `    base_input = state.get("input") or (state["messages"][-1].content if state.get("messages") else "")`,
    );
    if (ups.length) {
      lines.push(`    # Aggregate upstream outputs so this node can act on them`);
      lines.push(`    context_parts = []`);
      for (const u of ups) {
        const key = safePy(u.outputVar);
        const label = u.label.replace(/"/g, '\\"');
        lines.push(
          `    if state.get("${key}"): context_parts.append(f"--- ${label} (${key}) ---\\n{state['${key}']}")`,
        );
      }
      lines.push(`    context_block = "\\n\\n".join(context_parts)`);
      lines.push(
        `    human_text = f"Original input:\\n{base_input}\\n\\nUpstream results:\\n{context_block}" if context_block else base_input`,
      );
    } else {
      lines.push(`    human_text = base_input`);
    }
    lines.push(`    human = HumanMessage(content=human_text)`);
    if (agentTools.length) {
      lines.push(`    # Tools are bound so the model can REQUEST them. This graph does NOT run a`);
      lines.push(
        `    # tool-execution loop — add a ToolNode + conditional edge for full execution.`,
      );
      lines.push(
        `    response = model_${safePy(a.id)}.bind_tools([${agentTools.join(", ")}]).invoke([system, human])`,
      );
    } else {
      lines.push(`    response = model_${safePy(a.id)}.invoke([system, human])`);
    }
    if (outVar && !reserved.has(outVar)) {
      lines.push(`    return {"messages": [response], "${outVar}": response.content}`);
    } else {
      lines.push(`    return {"messages": [response]}`);
    }
    lines.push(``);
  }

  // Condition nodes
  for (const c of conditionNodes) {
    const fn = safePy(c.label || c.id);
    const prompt = JSON.stringify(c.conditionPrompt || "Decide which path to take.");
    const outs = outEdges(c.id, edges);
    const labels = outs.map((e) => e.label || "default").filter(Boolean);
    lines.push(`def ${fn}_router(state: SwarmState) -> str:`);
    lines.push(`    """Condition: ${c.label}"""`);
    lines.push(`    last_content = state["messages"][-1].content if state["messages"] else ""`);
    lines.push(`    # TODO: implement routing logic based on: ${prompt}`);
    lines.push(`    # Return one of: ${JSON.stringify(labels)}`);
    lines.push(`    return ${JSON.stringify(labels[0] || "default")}`);
    lines.push(``);
  }

  // Approval nodes
  for (const ap of approvalNodes) {
    const fn = safePy(ap.label || ap.id);
    lines.push(`def ${fn}_node(state: SwarmState) -> dict:`);
    lines.push(`    """HITL approval: ${ap.approvalTitle || ap.label}"""`);
    lines.push(
      `    answer = interrupt({"question": ${JSON.stringify(ap.approvalTitle || "Approve?")}, "risk": ${JSON.stringify(ap.approvalRisk || "medium")}})`,
    );
    lines.push(`    return {"messages": [HumanMessage(content=f"Approval: {answer}")]}`);
    lines.push(``);
  }

  // Loop nodes
  for (const lp of loopNodes) {
    const fn = safePy(lp.label || lp.id);
    lines.push(`def ${fn}_node(state: SwarmState) -> dict:`);
    lines.push(`    """Loop: ${lp.label} (max ${lp.maxIters ?? 3} iterations)"""`);
    lines.push(`    # TODO: implement loop body`);
    lines.push(`    return {"messages": [HumanMessage(content="Loop iteration")]}`);
    lines.push(``);
  }

  // Evaluate / Function / A2A nodes — runnable passthrough stubs
  for (const ev of evaluateNodes) {
    const fn = safePy(ev.label || ev.id);
    const outVar = ev.outputVar ? safePy(ev.outputVar) : null;
    const metrics = (ev.evalMetrics || []).map((m) => m.name).join(", ") || "overall";
    lines.push(`def ${fn}_node(state: SwarmState) -> dict:`);
    lines.push(`    """Evaluate (LLM-as-judge): ${ev.label}. Metrics: ${metrics}"""`);
    lines.push(`    last = state["messages"][-1].content if state["messages"] else ""`);
    lines.push(`    # TODO: score \`last\` against your rubric and metrics (${metrics}).`);
    lines.push(`    verdict = "PASS"  # placeholder`);
    if (outVar && !reserved.has(outVar)) {
      lines.push(`    return {"messages": [HumanMessage(content=verdict)], "${outVar}": verdict}`);
    } else {
      lines.push(`    return {"messages": [HumanMessage(content=verdict)]}`);
    }
    lines.push(``);
  }
  for (const fnode of functionNodes) {
    const fn = safePy(fnode.label || fnode.id);
    const outVar = fnode.outputVar ? safePy(fnode.outputVar) : null;
    lines.push(`def ${fn}_node(state: SwarmState) -> dict:`);
    lines.push(`    """Function transform: ${fnode.label}"""`);
    lines.push(`    last = state["messages"][-1].content if state["messages"] else ""`);
    if (fnode.functionCode) {
      lines.push(`    # Original JS transform from AgentSwarms — port to Python:`);
      for (const codeLine of fnode.functionCode.split("\n")) {
        lines.push(`    #   ${codeLine}`);
      }
    }
    lines.push(`    result = last  # TODO: implement transform`);
    if (outVar && !reserved.has(outVar)) {
      lines.push(`    return {"messages": [HumanMessage(content=result)], "${outVar}": result}`);
    } else {
      lines.push(`    return {"messages": [HumanMessage(content=result)]}`);
    }
    lines.push(``);
  }
  for (const a2a of a2aNodes) {
    const fn = safePy(a2a.label || a2a.id);
    const outVar = a2a.outputVar ? safePy(a2a.outputVar) : null;
    const endpoint = JSON.stringify(a2a.a2aEndpoint || "https://your-a2a-endpoint.example/invoke");
    lines.push(`def ${fn}_node(state: SwarmState) -> dict:`);
    lines.push(`    """Remote A2A agent: ${a2a.label}"""`);
    lines.push(`    last = state["messages"][-1].content if state["messages"] else ""`);
    lines.push(`    payload = json.dumps({"message": last}).encode()`);
    lines.push(
      `    req = urllib.request.Request(${endpoint}, data=payload, headers={"Content-Type": "application/json"})`,
    );
    lines.push(`    try:`);
    lines.push(`        with urllib.request.urlopen(req, timeout=60) as resp:`);
    lines.push(`            out = resp.read().decode()`);
    lines.push(`    except Exception as e:  # noqa: BLE001`);
    lines.push(`        out = f"A2A call failed: {e}"`);
    if (outVar && !reserved.has(outVar)) {
      lines.push(`    return {"messages": [HumanMessage(content=out)], "${outVar}": out}`);
    } else {
      lines.push(`    return {"messages": [HumanMessage(content=out)]}`);
    }
    lines.push(``);
  }

  // Build graph
  lines.push(`# ── Build graph ──`);
  lines.push(`graph = StateGraph(SwarmState)`);
  lines.push(``);

  // Add all nodes
  for (const a of agentNodes)
    lines.push(`graph.add_node("${safePy(a.label || a.id)}", ${safePy(a.label || a.id)}_node)`);
  for (const ap of approvalNodes)
    lines.push(`graph.add_node("${safePy(ap.label || ap.id)}", ${safePy(ap.label || ap.id)}_node)`);
  for (const lp of loopNodes)
    lines.push(`graph.add_node("${safePy(lp.label || lp.id)}", ${safePy(lp.label || lp.id)}_node)`);
  for (const o of otherNodes)
    lines.push(`graph.add_node("${safePy(o.label || o.id)}", ${safePy(o.label || o.id)}_node)`);
  lines.push(``);

  // START edges — only nodes that have NO upstream non-input dependencies.
  // This prevents racing aggregator nodes (e.g. a Chief Magistrate) against
  // their own upstream judges when the canvas connected the input pill to
  // every node for convenience.
  const startTargets = new Set<string>();
  for (const e of edges) {
    if (!inputIds.has(e.source)) continue;
    const target = nodes.find((n) => n.id === e.target);
    if (!target || conditionIds.has(target.id)) continue;
    const hasUpstream = edges.some(
      (other) => other.target === target.id && !inputIds.has(other.source),
    );
    if (hasUpstream) continue; // downstream node — let upstream nodes drive it
    startTargets.add(target.id);
  }
  for (const id of startTargets) {
    const t = nodes.find((n) => n.id === id)!;
    lines.push(`graph.add_edge(START, "${safePy(t.label || t.id)}")`);
  }
  // Fallback: a graph with no START edge fails to compile ("must have an
  // entrypoint"). If the topology gave us none (no input pill, or a fully
  // interconnected cluster), seed START from the first agent node.
  if (!startTargets.size && agentNodes.length) {
    const first = agentNodes[0];
    lines.push(`# No input-rooted entrypoint detected — defaulting START to the first agent.`);
    lines.push(`graph.add_edge(START, "${safePy(first.label || first.id)}")`);
  }

  // Regular edges
  for (const e of edges) {
    if (inputIds.has(e.source) || inputIds.has(e.target)) continue;
    const src = nodes.find((n) => n.id === e.source);
    const tgt = nodes.find((n) => n.id === e.target);
    if (!src || !tgt) continue;
    if (conditionIds.has(src.id)) continue; // handled as conditional edges
    // Condition nodes are NOT real graph nodes — they become conditional-edge
    // routers attached to their upstream node. Emitting a plain edge into one
    // would reference a node that was never added → compile error.
    if (conditionIds.has(tgt.id)) continue;

    const srcName = safePy(src.label || src.id);
    const tgtName = outputIds.has(tgt.id) ? "END" : `"${safePy(tgt.label || tgt.id)}"`;
    lines.push(`graph.add_edge("${srcName}", ${tgtName})`);
  }

  // Conditional edges
  for (const c of conditionNodes) {
    const fn = safePy(c.label || c.id);
    const outs = outEdges(c.id, edges);
    const mapping: Record<string, string> = {};

    const inEdge = edges.find((e) => e.target === c.id);
    const inNode = inEdge ? nodes.find((n) => n.id === inEdge.source) : null;
    if (inNode && !inputIds.has(inNode.id)) {
      for (const out of outs) {
        const tgt = nodes.find((n) => n.id === out.target);
        if (tgt) {
          const label = out.label || "default";
          mapping[label] = outputIds.has(tgt.id) ? "END" : safePy(tgt.label || tgt.id);
        }
      }
      const mapStr = Object.entries(mapping)
        .map(([k, v]) => `"${k}": ${v === "END" ? "END" : `"${v}"`}`)
        .join(", ");
      lines.push(
        `graph.add_conditional_edges("${safePy(inNode.label || inNode.id)}", ${fn}_router, {${mapStr}})`,
      );
    }
  }

  lines.push(``);
  if (approvalNodes.length) {
    // interrupt() requires a checkpointer + a thread id on every invoke.
    lines.push(`app = graph.compile(checkpointer=MemorySaver())`);
    lines.push(``);
    lines.push(`if __name__ == "__main__":`);
    lines.push(`    config = {"configurable": {"thread_id": "1"}}`);
    lines.push(
      `    result = app.invoke({"messages": [], "input": "Hello, run the swarm!"}, config=config)`,
    );
    lines.push(`    for msg in result["messages"]:`);
    lines.push(`        print(f"{msg.type}: {msg.content[:200]}")`);
    lines.push(`    # On an approval interrupt, resume with:`);
    lines.push(`    #   from langgraph.types import Command`);
    lines.push(`    #   app.invoke(Command(resume="approved"), config=config)`);
  } else {
    lines.push(`app = graph.compile()`);
    lines.push(``);
    lines.push(`if __name__ == "__main__":`);
    lines.push(`    result = app.invoke({"messages": [], "input": "Hello, run the swarm!"})`);
    lines.push(`    for msg in result["messages"]:`);
    lines.push(`        print(f"{msg.type}: {msg.content[:200]}")`);
  }

  return lines.join("\n");
}

/* ────────────────────────────────────────────────────────────────────────
   TypeScript generator
   ──────────────────────────────────────────────────────────────────────── */

export function buildLangGraphTypeScriptSwarm(swarm: PortableSwarm): string {
  const { edges } = swarm;
  const nodes = disambiguateLabels(swarm.nodes);
  const byKind = groupByKind(nodes);
  const agentNodes = byKind["agent"] || [];
  const conditionNodes = byKind["condition"] || [];
  const approvalNodes = byKind["approval"] || [];
  const loopNodes = byKind["loop"] || [];
  const inputNodes = byKind["input"] || [];
  const outputNodes = byKind["output"] || [];
  const evaluateNodes = byKind["evaluate"] || [];
  const functionNodes = byKind["function"] || [];
  const a2aNodes = byKind["a2a_remote"] || [];
  const otherNodes = [...evaluateNodes, ...functionNodes, ...a2aNodes];

  const tools = collectTools(agentNodes);
  const anyTools = tools.length > 0;

  const modelImports = new Map<string, { importLine: string; cls: string }>();
  for (const a of agentNodes) {
    const fam = detectFamily(a.provider, a.model);
    const mi = tsModelImport(fam);
    modelImports.set(mi.cls, mi);
  }
  if (!modelImports.size) modelImports.set("ChatOpenAI", tsModelImport("openai"));

  const reserved = new Set(["messages", "input"]);
  const outputVars = new Set<string>();
  for (const n of nodes) {
    if (!n.outputVar) continue;
    const safe = safeTs(n.outputVar);
    if (reserved.has(safe)) continue;
    outputVars.add(safe);
  }

  const conditionIds = new Set(conditionNodes.map((c) => c.id));
  const inputIds = new Set(inputNodes.map((n) => n.id));
  const outputIds = new Set(outputNodes.map((n) => n.id));

  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * LangGraph swarm: ${swarm.name}`);
  lines.push(` * Generated by AgentSwarm — https://agentswarms.fyi`);
  lines.push(` *`);
  for (const n of FIDELITY_NOTE) lines.push(` * ${n}`);
  lines.push(` *`);
  lines.push(` * !! ${MODEL_ID_WARNING}`);
  lines.push(` *`);
  lines.push(` * Install:`);
  lines.push(
    ` *   npm install @langchain/langgraph @langchain/core @langchain/openai @langchain/anthropic @langchain/google-genai${anyTools ? " zod" : ""}`,
  );
  lines.push(` *`);
  lines.push(` * Run:`);
  lines.push(
    ` *   # Set the API key(s) matching your model providers (OPENAI_API_KEY, ANTHROPIC_API_KEY, GOOGLE_API_KEY)`,
  );
  lines.push(` *   npx tsx ${safeTs(swarm.name)}_langgraph.ts`);
  lines.push(` */`);
  for (const mi of modelImports.values()) lines.push(mi.importLine);
  lines.push(
    `import { HumanMessage, SystemMessage, type BaseMessage } from "@langchain/core/messages";`,
  );
  if (anyTools) {
    lines.push(`import { tool } from "@langchain/core/tools";`);
    lines.push(`import { z } from "zod";`);
  }
  lines.push(`import { Annotation, StateGraph, START, END } from "@langchain/langgraph";`);
  if (approvalNodes.length) {
    lines.push(`import { interrupt, MemorySaver } from "@langchain/langgraph";`);
  }
  lines.push(``);

  // State annotation
  lines.push(`// ── State ──`);
  lines.push(`const SwarmState = Annotation.Root({`);
  lines.push(
    `  messages: Annotation<BaseMessage[]>({ reducer: (a, b) => [...a, ...b], default: () => [] }),`,
  );
  lines.push(`  input: Annotation<string>({ default: () => "" }),`);
  for (const v of outputVars) {
    lines.push(`  ${v}: Annotation<string>({ default: () => "" }),`);
  }
  lines.push(`});`);
  lines.push(``);

  // Tool stubs (shared across agents that enable them)
  if (anyTools) {
    lines.push(`// ── Tools (stubs — implement each body; hosted tools are not portable) ──`);
    for (const t of tools) {
      const fn = safeTs(t);
      lines.push(`const ${fn} = tool(`);
      lines.push(`  async ({ query }: { query: string }) => {`);
      lines.push(`    // TODO: implement ${fn}`);
      lines.push(`    return \`TODO: implement ${fn} for: \${query}\`;`);
      lines.push(`  },`);
      lines.push(`  {`);
      lines.push(`    name: ${JSON.stringify(t)},`);
      lines.push(`    description: ${JSON.stringify(toolDescription(t))},`);
      lines.push(`    schema: z.object({ query: z.string().describe("The input query") }),`);
      lines.push(`  },`);
      lines.push(`);`);
      lines.push(``);
    }
  }

  // Models
  lines.push(`// ── Models ──`);
  for (const a of agentNodes) {
    const fam = detectFamily(a.provider, a.model);
    const mi = tsModelImport(fam);
    lines.push(
      `const model_${safeTs(a.id)} = new ${mi.cls}({ model: "${cleanModelId(a.model)}", temperature: ${a.temperature ?? 0.7} });`,
    );
  }
  lines.push(``);

  // Agent nodes
  lines.push(`// ── Agent nodes ──`);
  for (const a of agentNodes) {
    const fn = safeTs(a.label || a.id);
    const sysMsg = JSON.stringify(a.systemPrompt || `You are ${a.label}.`);
    const outVar = a.outputVar ? safeTs(a.outputVar) : null;
    const ups = upstreamOutputVars(a.id, nodes, edges);
    const agentTools = (a.enabledTools || []).map((t) => safeTs(t));

    lines.push(`async function ${fn}_node(state: typeof SwarmState.State) {`);
    lines.push(`  const system = new SystemMessage(${sysMsg});`);
    lines.push(
      `  const baseInput = state.input || state.messages[state.messages.length - 1]?.content?.toString() || "";`,
    );
    if (ups.length) {
      lines.push(`  const parts: string[] = [];`);
      for (const u of ups) {
        const key = safeTs(u.outputVar);
        const label = u.label.replace(/`/g, "\\`");
        lines.push(
          `  if ((state as any).${key}) parts.push(\`--- ${label} (${key}) ---\\n\${(state as any).${key}}\`);`,
        );
      }
      lines.push(`  const contextBlock = parts.join("\\n\\n");`);
      lines.push(
        `  const humanText = contextBlock ? \`Original input:\\n\${baseInput}\\n\\nUpstream results:\\n\${contextBlock}\` : baseInput;`,
      );
    } else {
      lines.push(`  const humanText = baseInput;`);
    }
    lines.push(`  const human = new HumanMessage(humanText);`);
    if (agentTools.length) {
      lines.push(`  // Tools are bound so the model can REQUEST them. This graph does NOT run a`);
      lines.push(
        `  // tool-execution loop — add a ToolNode + conditional edge for full execution.`,
      );
      lines.push(
        `  const response = await model_${safeTs(a.id)}.bindTools([${agentTools.join(", ")}]).invoke([system, human]);`,
      );
    } else {
      lines.push(`  const response = await model_${safeTs(a.id)}.invoke([system, human]);`);
    }
    if (outVar && !reserved.has(outVar)) {
      lines.push(`  return { messages: [response], ${outVar}: response.content as string };`);
    } else {
      lines.push(`  return { messages: [response] };`);
    }
    lines.push(`}`);
    lines.push(``);
  }

  // Condition routers
  for (const c of conditionNodes) {
    const fn = safeTs(c.label || c.id);
    const outs = outEdges(c.id, edges);
    const labels = outs.map((e) => e.label || "default");
    lines.push(`function ${fn}_router(state: typeof SwarmState.State): string {`);
    lines.push(`  // TODO: implement routing logic`);
    lines.push(`  // Return one of: ${JSON.stringify(labels)}`);
    lines.push(`  return ${JSON.stringify(labels[0] || "default")};`);
    lines.push(`}`);
    lines.push(``);
  }

  // Approval nodes
  for (const ap of approvalNodes) {
    const fn = safeTs(ap.label || ap.id);
    lines.push(`async function ${fn}_node(state: typeof SwarmState.State) {`);
    lines.push(
      `  const answer = interrupt({ question: ${JSON.stringify(ap.approvalTitle || "Approve?")}, risk: ${JSON.stringify(ap.approvalRisk || "medium")} });`,
    );
    lines.push(`  return { messages: [new HumanMessage(\`Approval: \${answer}\`)] };`);
    lines.push(`}`);
    lines.push(``);
  }

  // Loop nodes
  for (const lp of loopNodes) {
    const fn = safeTs(lp.label || lp.id);
    lines.push(`async function ${fn}_node(state: typeof SwarmState.State) {`);
    lines.push(`  // TODO: implement loop body (max ${lp.maxIters ?? 3} iterations)`);
    lines.push(`  return { messages: [new HumanMessage("Loop iteration")] };`);
    lines.push(`}`);
    lines.push(``);
  }

  // Evaluate / Function / A2A nodes — runnable passthrough stubs
  for (const ev of evaluateNodes) {
    const fn = safeTs(ev.label || ev.id);
    const outVar = ev.outputVar ? safeTs(ev.outputVar) : null;
    const metrics = (ev.evalMetrics || []).map((m) => m.name).join(", ") || "overall";
    lines.push(`async function ${fn}_node(state: typeof SwarmState.State) {`);
    lines.push(`  // Evaluate (LLM-as-judge): ${ev.label}. Metrics: ${metrics}`);
    lines.push(
      `  const last = state.messages[state.messages.length - 1]?.content?.toString() || "";`,
    );
    lines.push(`  // TODO: score \`last\` against your rubric and metrics (${metrics}).`);
    lines.push(`  const verdict = "PASS"; // placeholder`);
    if (outVar && !reserved.has(outVar)) {
      lines.push(`  return { messages: [new HumanMessage(verdict)], ${outVar}: verdict };`);
    } else {
      lines.push(`  return { messages: [new HumanMessage(verdict)] };`);
    }
    lines.push(`}`);
    lines.push(``);
  }
  for (const fnode of functionNodes) {
    const fn = safeTs(fnode.label || fnode.id);
    const outVar = fnode.outputVar ? safeTs(fnode.outputVar) : null;
    lines.push(`async function ${fn}_node(state: typeof SwarmState.State) {`);
    lines.push(`  // Function transform: ${fnode.label}`);
    lines.push(
      `  const last = state.messages[state.messages.length - 1]?.content?.toString() || "";`,
    );
    if (fnode.functionCode) {
      lines.push(`  // Original AgentSwarms sandbox transform:`);
      for (const codeLine of fnode.functionCode.split("\n")) {
        lines.push(`  //   ${codeLine}`);
      }
    }
    lines.push(`  const result = last; // TODO: implement transform`);
    if (outVar && !reserved.has(outVar)) {
      lines.push(`  return { messages: [new HumanMessage(result)], ${outVar}: result };`);
    } else {
      lines.push(`  return { messages: [new HumanMessage(result)] };`);
    }
    lines.push(`}`);
    lines.push(``);
  }
  for (const a2a of a2aNodes) {
    const fn = safeTs(a2a.label || a2a.id);
    const outVar = a2a.outputVar ? safeTs(a2a.outputVar) : null;
    const endpoint = JSON.stringify(a2a.a2aEndpoint || "https://your-a2a-endpoint.example/invoke");
    lines.push(`async function ${fn}_node(state: typeof SwarmState.State) {`);
    lines.push(`  // Remote A2A agent: ${a2a.label}`);
    lines.push(
      `  const last = state.messages[state.messages.length - 1]?.content?.toString() || "";`,
    );
    lines.push(`  let out: string;`);
    lines.push(`  try {`);
    lines.push(`    const resp = await fetch(${endpoint}, {`);
    lines.push(`      method: "POST",`);
    lines.push(`      headers: { "Content-Type": "application/json" },`);
    lines.push(`      body: JSON.stringify({ message: last }),`);
    lines.push(`    });`);
    lines.push(`    out = await resp.text();`);
    lines.push(`  } catch (e) {`);
    lines.push(`    out = \`A2A call failed: \${e instanceof Error ? e.message : String(e)}\`;`);
    lines.push(`  }`);
    if (outVar && !reserved.has(outVar)) {
      lines.push(`  return { messages: [new HumanMessage(out)], ${outVar}: out };`);
    } else {
      lines.push(`  return { messages: [new HumanMessage(out)] };`);
    }
    lines.push(`}`);
    lines.push(``);
  }

  // Build graph
  lines.push(`// ── Build graph ──`);
  lines.push(`const graph = new StateGraph(SwarmState)`);
  for (const a of agentNodes)
    lines.push(`  .addNode("${safeTs(a.label || a.id)}", ${safeTs(a.label || a.id)}_node)`);
  for (const ap of approvalNodes)
    lines.push(`  .addNode("${safeTs(ap.label || ap.id)}", ${safeTs(ap.label || ap.id)}_node)`);
  for (const lp of loopNodes)
    lines.push(`  .addNode("${safeTs(lp.label || lp.id)}", ${safeTs(lp.label || lp.id)}_node)`);
  for (const o of otherNodes)
    lines.push(`  .addNode("${safeTs(o.label || o.id)}", ${safeTs(o.label || o.id)}_node)`);

  // START edges — skip nodes that also have upstream non-input predecessors
  const startTargets = new Set<string>();
  for (const e of edges) {
    if (!inputIds.has(e.source)) continue;
    const target = nodes.find((n) => n.id === e.target);
    if (!target || conditionIds.has(target.id)) continue;
    const hasUpstream = edges.some(
      (other) => other.target === target.id && !inputIds.has(other.source),
    );
    if (hasUpstream) continue;
    startTargets.add(target.id);
  }
  for (const id of startTargets) {
    const t = nodes.find((n) => n.id === id)!;
    lines.push(`  .addEdge(START, "${safeTs(t.label || t.id)}")`);
  }
  // Fallback entrypoint (see Python generator note).
  if (!startTargets.size && agentNodes.length) {
    const first = agentNodes[0];
    lines.push(`  // No input-rooted entrypoint detected — defaulting START to the first agent.`);
    lines.push(`  .addEdge(START, "${safeTs(first.label || first.id)}")`);
  }

  // Regular edges
  for (const e of edges) {
    if (inputIds.has(e.source) || inputIds.has(e.target)) continue;
    const src = nodes.find((n) => n.id === e.source);
    const tgt = nodes.find((n) => n.id === e.target);
    if (!src || !tgt) continue;
    if (conditionIds.has(src.id)) continue;
    // Conditions become conditional-edge routers on their upstream node, not
    // standalone graph nodes — skip plain edges into them to avoid referencing
    // a node that was never added.
    if (conditionIds.has(tgt.id)) continue;

    const srcName = safeTs(src.label || src.id);
    const tgtName = outputIds.has(tgt.id) ? "END" : `"${safeTs(tgt.label || tgt.id)}"`;
    if (tgtName === "END") {
      lines.push(`  .addEdge("${srcName}", END)`);
    } else {
      lines.push(`  .addEdge("${srcName}", ${tgtName})`);
    }
  }

  // Conditional edges
  for (const c of conditionNodes) {
    const fn = safeTs(c.label || c.id);
    const outs = outEdges(c.id, edges);
    const inEdge = edges.find((e) => e.target === c.id);
    const inNode = inEdge ? nodes.find((n) => n.id === inEdge.source) : null;
    if (inNode && !inputIds.has(inNode.id)) {
      const mapping: string[] = [];
      for (const out of outs) {
        const tgt = nodes.find((n) => n.id === out.target);
        if (tgt) {
          const label = out.label || "default";
          const val = outputIds.has(tgt.id) ? "END" : `"${safeTs(tgt.label || tgt.id)}"`;
          mapping.push(`"${label}": ${val}`);
        }
      }
      lines.push(
        `  .addConditionalEdges("${safeTs(inNode.label || inNode.id)}", ${fn}_router, { ${mapping.join(", ")} })`,
      );
    }
  }

  if (approvalNodes.length) {
    lines.push(`  .compile({ checkpointer: new MemorySaver() });`);
    lines.push(``);
    lines.push(`async function main() {`);
    lines.push(`  // interrupt() requires a thread id on every invoke.`);
    lines.push(`  const config = { configurable: { thread_id: "1" } };`);
    lines.push(
      `  const result = await graph.invoke({ messages: [], input: "Hello, run the swarm!" }, config);`,
    );
    lines.push(`  for (const msg of result.messages) {`);
    lines.push(
      `    console.log(\`\${msg._getType()}: \${(msg.content as string).slice(0, 200)}\`);`,
    );
    lines.push(`  }`);
    lines.push(`  // On an approval interrupt, resume with:`);
    lines.push(`  //   import { Command } from "@langchain/langgraph";`);
    lines.push(`  //   await graph.invoke(new Command({ resume: "approved" }), config);`);
    lines.push(`}`);
  } else {
    lines.push(`  .compile();`);
    lines.push(``);
    lines.push(`async function main() {`);
    lines.push(
      `  const result = await graph.invoke({ messages: [], input: "Hello, run the swarm!" });`,
    );
    lines.push(`  for (const msg of result.messages) {`);
    lines.push(
      `    console.log(\`\${msg._getType()}: \${(msg.content as string).slice(0, 200)}\`);`,
    );
    lines.push(`  }`);
    lines.push(`}`);
  }
  lines.push(``);
  lines.push(`main();`);

  return lines.join("\n");
}

/* ────────────────────────────────────────────────────────────────────────
   Download helpers
   ──────────────────────────────────────────────────────────────────────── */

export function downloadSwarmAsLangGraph(swarm: PortableSwarm, lang: "python" | "typescript") {
  const safeName =
    swarm.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "swarm";
  if (lang === "python") {
    downloadFile(`${safeName}_langgraph.py`, buildLangGraphPythonSwarm(swarm), "text/x-python");
  } else {
    downloadFile(
      `${safeName}_langgraph.ts`,
      buildLangGraphTypeScriptSwarm(swarm),
      "text/typescript",
    );
  }
}
