/**
 * Convert a PortableSwarm graph into runnable Strands Agents SDK code
 * (Python or TypeScript).
 *
 * Strands (https://strandsagents.com) is AWS's open-source, model-driven agent
 * SDK. Only `agent` nodes map cleanly onto its primitives; control-flow nodes
 * (condition / loop / approval / evaluate / function / a2a_remote) are surfaced
 * as comments so the generated file stays runnable and the author knows what to
 * wire up manually — mirroring the CrewAI / OpenAI Agents exporters.
 *
 * Python uses the deterministic multi-agent Graph (`GraphBuilder`). The
 * TypeScript SDK's multi-agent Graph is still experimental, so we emit explicit
 * topological orchestration over the confirmed `Agent.invoke()` API instead.
 *
 * Generated by AgentSwarm — https://agentswarms.fyi
 */
import type { PortableSwarm, PortableSwarmNode, PortableSwarmEdge } from "./swarmPortable";
import { downloadFile } from "./agentExport";
import {
  cleanModelId,
  toolDescription,
  MODEL_ID_WARNING,
  FIDELITY_NOTE,
  bridgeAgentEdges,
  bridgedEntryAgents,
  viaSuffix,
} from "./swarmExportTools";

function safePy(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^(\d)/, "_$1") || "node";
}

type Family = "google" | "anthropic" | "openai";

function detectFamily(provider?: string, model?: string): Family {
  const p = (provider || "").toLowerCase();
  const m = (model || "").toLowerCase();
  if (p.includes("anthropic") || m.startsWith("anthropic/") || m.startsWith("claude-"))
    return "anthropic";
  if (
    p.includes("google") ||
    p.includes("gemini") ||
    p.includes("vertex") ||
    m.startsWith("google/") ||
    m.startsWith("gemini-") ||
    m.includes("/gemini-")
  ) {
    return "google";
  }
  return "openai";
}

function agentNodes(nodes: PortableSwarmNode[]): PortableSwarmNode[] {
  return nodes.filter((n) => n.kind === "agent");
}

/** Unique, ordered list of tool ids enabled across the given agent nodes. */
function collectTools(agents: PortableSwarmNode[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const a of agents) {
    for (const t of a.enabledTools || []) {
      if (!seen.has(t)) {
        seen.add(t);
        out.push(t);
      }
    }
  }
  return out;
}

/**
 * Topological order of agent nodes (Kahn), over BRIDGED edges so a dependency
 * that runs through a condition/approval/function node still orders correctly.
 * Falls back to input order on cycles.
 */
function topoAgents(nodes: PortableSwarmNode[], edges: PortableSwarmEdge[]): PortableSwarmNode[] {
  const agents = agentNodes(nodes);
  const bridged = bridgeAgentEdges(nodes, edges);
  const indeg = new Map<string, number>();
  agents.forEach((a) => indeg.set(a.id, 0));
  for (const e of bridged) indeg.set(e.target, (indeg.get(e.target) ?? 0) + 1);
  const queue = agents.filter((a) => (indeg.get(a.id) ?? 0) === 0).map((a) => a.id);
  const ordered: string[] = [];
  while (queue.length) {
    const id = queue.shift()!;
    ordered.push(id);
    for (const e of bridged) {
      if (e.source !== id) continue;
      const d = (indeg.get(e.target) ?? 0) - 1;
      indeg.set(e.target, d);
      if (d === 0) queue.push(e.target);
    }
  }
  for (const a of agents) if (!ordered.includes(a.id)) ordered.push(a.id);
  return ordered.map((id) => agents.find((a) => a.id === id)!);
}

/** Stable, unique, human-readable string key per agent (for graph node ids). */
function nodeKeys(agents: PortableSwarmNode[]): Map<string, string> {
  const used = new Set<string>();
  const map = new Map<string, string>();
  for (const a of agents) {
    const base = safePy(a.label || a.id) || "node";
    let key = base;
    let i = 2;
    while (used.has(key)) key = `${base}_${i++}`;
    used.add(key);
    map.set(a.id, key);
  }
  return map;
}

function controlFlowNote(nodes: PortableSwarmNode[]): string[] {
  const kinds = ["condition", "loop", "approval", "evaluate", "function", "a2a_remote"];
  const present = nodes.filter((n) => kinds.includes(n.kind));
  if (!present.length) return [];
  const lines: string[] = [];
  lines.push(`# NOTE: this swarm also contains control-flow nodes that do not map`);
  lines.push(`# directly onto Strands' Graph. Wire them up manually:`);
  for (const n of present) lines.push(`#   - ${n.kind}: "${n.label}"`);
  return lines;
}

/* ── Model expressions ─────────────────────────────────────────────────── */

function pyModelImport(fam: Family): string {
  if (fam === "anthropic") return "from strands.models.anthropic import AnthropicModel";
  if (fam === "google") return "from strands.models.gemini import GeminiModel";
  return "from strands.models.openai import OpenAIModel";
}

function pyModelExpr(a: PartialModel): string {
  const fam = detectFamily(a.provider, a.model);
  const id = cleanModelId(a.model);
  const t = a.temperature ?? 0.7;
  if (fam === "anthropic") {
    return `AnthropicModel(client_args={"api_key": os.environ.get("ANTHROPIC_API_KEY")}, model_id="${id}", max_tokens=4096, params={"temperature": ${t}})`;
  }
  if (fam === "google") {
    return `GeminiModel(client_args={"api_key": os.environ.get("GEMINI_API_KEY")}, model_id="${id}", params={"temperature": ${t}})`;
  }
  return `OpenAIModel(client_args={"api_key": os.environ.get("OPENAI_API_KEY")}, model_id="${id}", params={"temperature": ${t}})`;
}

function tsModelImport(fam: Family): string {
  if (fam === "anthropic")
    return 'import { AnthropicModel } from "@strands-agents/sdk/models/anthropic";';
  if (fam === "google") return 'import { GoogleModel } from "@strands-agents/sdk/models/google";';
  return 'import { OpenAIModel } from "@strands-agents/sdk/models/openai";';
}

function tsModelExpr(a: PartialModel): string {
  const fam = detectFamily(a.provider, a.model);
  const id = cleanModelId(a.model);
  const t = a.temperature ?? 0.7;
  if (fam === "anthropic") {
    return `new AnthropicModel({ apiKey: process.env.ANTHROPIC_API_KEY, modelId: "${id}", maxTokens: 4096, params: { temperature: ${t} } })`;
  }
  if (fam === "google") {
    return `new GoogleModel({ apiKey: process.env.GEMINI_API_KEY, modelId: "${id}", params: { temperature: ${t} } })`;
  }
  return `new OpenAIModel({ api: "chat", apiKey: process.env.OPENAI_API_KEY, modelId: "${id}", temperature: ${t} })`;
}

type PartialModel = { provider?: string; model?: string; temperature?: number };

/* ────────────────────────────────────────────────────────────────────────
   Python generator (multi-agent Graph via GraphBuilder)
   ──────────────────────────────────────────────────────────────────────── */

export function buildStrandsPythonSwarm(swarm: PortableSwarm): string {
  const { nodes, edges } = swarm;
  const ordered = topoAgents(nodes, edges);
  const tools = collectTools(ordered);
  const anyTools = tools.length > 0;
  const keys = nodeKeys(ordered);
  // Bridged, not direct: a path Researcher -> [condition] -> Writer must still
  // connect the two agents, otherwise Writer becomes a second entry point and a
  // sequential pipeline silently turns into two parallel roots.
  const aEdges = bridgeAgentEdges(nodes, edges);
  const entries = bridgedEntryAgents(nodes, aEdges);

  const L: string[] = [];
  L.push(`"""Strands swarm: ${swarm.name}`);
  L.push(`Generated by AgentSwarm — https://agentswarms.fyi`);
  L.push(``);
  for (const n of FIDELITY_NOTE) L.push(n);
  L.push(``);
  L.push(`!! ${MODEL_ID_WARNING}`);
  L.push(``);
  L.push(`Install:`);
  L.push(`    pip install strands-agents strands-agents-tools`);
  L.push(``);
  L.push(`Run:`);
  L.push(`    # Set the API key(s) matching your model providers, e.g.:`);
  L.push(`    #   export OPENAI_API_KEY=...   (or ANTHROPIC_API_KEY / GEMINI_API_KEY)`);
  L.push(`    python ${safePy(swarm.name)}_strands.py`);
  L.push(`"""`);
  L.push(`import os`);
  L.push(`from strands import Agent${anyTools ? ", tool" : ""}`);
  L.push(`from strands.multiagent import GraphBuilder`);
  // Dedupe model imports by family.
  const famImports = new Set<string>();
  for (const a of ordered) famImports.add(pyModelImport(detectFamily(a.provider, a.model)));
  if (!famImports.size) famImports.add(pyModelImport("openai"));
  for (const imp of famImports) L.push(imp);
  L.push(``);

  if (!ordered.length) {
    L.push(`# This swarm has no agent nodes to export.`);
    return L.join("\n");
  }

  // Tool stubs
  if (anyTools) {
    L.push(`# ── Tools (stubs — implement each body; hosted tools are not portable) ──`);
    for (const t of tools) {
      const fn = safePy(t);
      L.push(`@tool`);
      L.push(`def ${fn}(query: str) -> str:`);
      L.push(`    """${toolDescription(t)}"""`);
      L.push(`    return f"TODO: implement ${fn} for: {query}"`);
      L.push(``);
    }
  }

  // Models
  L.push(`# ── Models ──`);
  for (const a of ordered) L.push(`model_${safePy(a.id)} = ${pyModelExpr(a)}`);
  L.push(``);

  // Agents
  L.push(`# ── Agents ──`);
  for (const a of ordered) {
    const v = `agent_${safePy(a.id)}`;
    const sys = JSON.stringify(a.systemPrompt || `You are ${a.label}, an AI agent.`);
    const agentTools = (a.enabledTools || []).map((t) => safePy(t));
    L.push(`${v} = Agent(`);
    L.push(`    model=model_${safePy(a.id)},`);
    L.push(`    system_prompt=${sys},`);
    if (agentTools.length) L.push(`    tools=[${agentTools.join(", ")}],`);
    L.push(`)`);
    L.push(``);
  }

  // Graph
  L.push(`# ── Build graph (deterministic DAG) ──`);
  L.push(`builder = GraphBuilder()`);
  for (const a of ordered) {
    L.push(`builder.add_node(agent_${safePy(a.id)}, ${JSON.stringify(keys.get(a.id)!)})`);
  }
  for (const e of aEdges) {
    if (e.via.length) L.push(`# bridged${viaSuffix(e.via, e.paths)}`);
    L.push(
      `builder.add_edge(${JSON.stringify(keys.get(e.source)!)}, ${JSON.stringify(keys.get(e.target)!)})`,
    );
  }
  for (const a of entries.length ? entries : [ordered[0]]) {
    L.push(`builder.set_entry_point(${JSON.stringify(keys.get(a.id)!)})`);
  }
  const cf = controlFlowNote(nodes);
  if (cf.length) {
    L.push(``);
    L.push(...cf);
  }
  L.push(``);
  L.push(`graph = builder.build()`);
  L.push(``);
  L.push(`if __name__ == "__main__":`);
  L.push(`    result = graph("Hello, run the swarm!")`);
  L.push(`    print(result)`);

  return L.join("\n");
}

/* ────────────────────────────────────────────────────────────────────────
   TypeScript generator (explicit topological orchestration)
   ──────────────────────────────────────────────────────────────────────── */

export function buildStrandsTypeScriptSwarm(swarm: PortableSwarm): string {
  const { nodes, edges } = swarm;
  const ordered = topoAgents(nodes, edges);
  const tools = collectTools(ordered);
  const anyTools = tools.length > 0;
  const keys = nodeKeys(ordered);
  // See the Python generator: bridge through unsupported node kinds so the
  // agent chain stays connected.
  const aEdges = bridgeAgentEdges(nodes, edges);

  const L: string[] = [];
  L.push(`/**`);
  L.push(` * Strands swarm: ${swarm.name}`);
  L.push(` * Generated by AgentSwarm — https://agentswarms.fyi`);
  L.push(` *`);
  for (const n of FIDELITY_NOTE) L.push(` * ${n}`);
  L.push(` *`);
  L.push(` * The Strands TypeScript SDK's multi-agent Graph is experimental, so this`);
  L.push(` * file runs the agents with explicit topological orchestration over the`);
  L.push(` * stable Agent.invoke() API. Swap in the Graph primitive once it stabilizes.`);
  L.push(` *`);
  L.push(` * !! ${MODEL_ID_WARNING}`);
  L.push(` *`);
  L.push(` * Install:`);
  L.push(` *   npm install @strands-agents/sdk${anyTools ? " zod" : ""}`);
  L.push(` *`);
  L.push(` * Run:`);
  L.push(` *   # Set the API key(s) matching your model providers`);
  L.push(` *   #   OPENAI_API_KEY / ANTHROPIC_API_KEY / GEMINI_API_KEY`);
  L.push(` *   npx tsx ${safePy(swarm.name)}_strands.ts`);
  L.push(` */`);
  L.push(`import { Agent${anyTools ? ", tool" : ""} } from "@strands-agents/sdk";`);
  const famImports = new Set<string>();
  for (const a of ordered) famImports.add(tsModelImport(detectFamily(a.provider, a.model)));
  if (!famImports.size) famImports.add(tsModelImport("openai"));
  for (const imp of famImports) L.push(imp);
  if (anyTools) L.push(`import z from "zod";`);
  L.push(``);

  if (!ordered.length) {
    L.push(`// This swarm has no agent nodes to export.`);
    return L.join("\n");
  }

  // Tool stubs
  if (anyTools) {
    L.push(`// ── Tools (stubs — implement each body; hosted tools are not portable) ──`);
    for (const t of tools) {
      const fn = safePy(t);
      L.push(`const ${fn} = tool({`);
      L.push(`  name: ${JSON.stringify(t)},`);
      L.push(`  description: ${JSON.stringify(toolDescription(t))},`);
      L.push(`  inputSchema: z.object({ query: z.string().describe("The input query") }),`);
      L.push(`  callback: (input) => {`);
      L.push(`    // TODO: implement ${fn}`);
      L.push(`    return \`TODO: implement ${fn} for: \${input.query}\`;`);
      L.push(`  },`);
      L.push(`});`);
      L.push(``);
    }
  }

  // Agents
  L.push(`// ── Agents ──`);
  for (const a of ordered) {
    const v = `agent_${safePy(a.id)}`;
    const sys = JSON.stringify(a.systemPrompt || `You are ${a.label}, an AI agent.`);
    const agentTools = (a.enabledTools || []).map((t) => safePy(t));
    L.push(`const ${v} = new Agent({`);
    L.push(`  model: ${tsModelExpr(a)},`);
    L.push(`  systemPrompt: ${sys},`);
    if (agentTools.length) L.push(`  tools: [${agentTools.join(", ")}],`);
    L.push(`  printer: false,`);
    L.push(`});`);
    L.push(``);
  }

  // Defensive text extraction (lastMessage shape varies across SDK versions).
  L.push(`// Pull plain text out of an invoke() result regardless of message shape.`);
  L.push(`function asText(result: any): string {`);
  L.push(`  const m = result?.lastMessage;`);
  L.push(`  if (typeof m === "string") return m;`);
  L.push(`  if (Array.isArray(m?.content))`);
  L.push(`    return m.content.map((b: any) => b?.text ?? "").join("");`);
  L.push(`  if (typeof m?.content === "string") return m.content;`);
  L.push(`  return m == null ? "" : JSON.stringify(m);`);
  L.push(`}`);
  L.push(``);

  // Orchestration — run agents in topological order, threading outputs forward.
  L.push(`async function main() {`);
  L.push(`  const input = "Hello, run the swarm!";`);
  L.push(`  const outputs: Record<string, string> = {};`);
  L.push(``);
  for (const a of ordered) {
    const key = keys.get(a.id)!;
    const ups = aEdges.filter((e) => e.target === a.id).map((e) => keys.get(e.source)!);
    L.push(`  // ${key}`);
    if (ups.length) {
      L.push(`  {`);
      L.push(
        `    const upstream = [${ups.map((u) => JSON.stringify(u)).join(", ")}].map((k) => outputs[k]).filter(Boolean);`,
      );
      L.push(
        `    const prompt = upstream.length ? \`Original input:\\n\${input}\\n\\nUpstream results:\\n\${upstream.join("\\n\\n")}\` : input;`,
      );
      L.push(`    const result = await agent_${safePy(a.id)}.invoke(prompt);`);
      L.push(`    outputs[${JSON.stringify(key)}] = asText(result);`);
      L.push(`    console.log("[${key}]", outputs[${JSON.stringify(key)}]);`);
      L.push(`  }`);
    } else {
      L.push(`  {`);
      L.push(`    const result = await agent_${safePy(a.id)}.invoke(input);`);
      L.push(`    outputs[${JSON.stringify(key)}] = asText(result);`);
      L.push(`    console.log("[${key}]", outputs[${JSON.stringify(key)}]);`);
      L.push(`  }`);
    }
  }
  const cf = controlFlowNote(nodes);
  if (cf.length) {
    L.push(``);
    for (const line of cf) L.push(`  ${line.replace(/^#/, "//")}`);
  }
  L.push(`}`);
  L.push(``);
  L.push(`main();`);

  return L.join("\n");
}

/* ────────────────────────────────────────────────────────────────────────
   Download helpers
   ──────────────────────────────────────────────────────────────────────── */

function safeFileName(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "swarm"
  );
}

export function downloadSwarmAsStrands(swarm: PortableSwarm, lang: "python" | "typescript") {
  if (lang === "python") {
    downloadFile(
      `${safeFileName(swarm.name)}_strands.py`,
      buildStrandsPythonSwarm(swarm),
      "text/x-python",
    );
  } else {
    downloadFile(
      `${safeFileName(swarm.name)}_strands.ts`,
      buildStrandsTypeScriptSwarm(swarm),
      "text/typescript",
    );
  }
}
