/**
 * Convert a PortableSwarm graph into runnable code for additional agent
 * frameworks: CrewAI and the OpenAI Agents SDK.
 *
 * Both target Python (the canonical SDK language for each). Only `agent`
 * nodes map cleanly onto these frameworks' primitives; control-flow nodes
 * (condition / loop / approval / evaluate / function / a2a_remote) are
 * surfaced as comments so the generated file stays runnable and the author
 * knows what to wire up manually.
 *
 * Generated by AgentSwarm — https://agentswarms.fyi
 */
import type { PortableSwarm, PortableSwarmNode, PortableSwarmEdge } from "./swarmPortable";
import { downloadFile } from "./agentExport";
import {
  cleanModelId,
  toolDescription,
  MODEL_ID_WARNING,
  FIDELITY_NOTE,
  bridgeAgentEdges,
  viaSuffix,
} from "./swarmExportTools";

function safePy(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^(\d)/, "_$1") || "node";
}

type Family = "google" | "anthropic" | "openai";

function detectFamily(provider?: string, model?: string): Family {
  const p = (provider || "").toLowerCase();
  const m = (model || "").toLowerCase();
  if (p.includes("anthropic") || m.startsWith("anthropic/") || m.startsWith("claude-"))
    return "anthropic";
  if (
    p.includes("google") ||
    p.includes("gemini") ||
    p.includes("vertex") ||
    m.startsWith("google/") ||
    m.startsWith("gemini-") ||
    m.includes("/gemini-")
  ) {
    return "google";
  }
  return "openai";
}

/**
 * LiteLLM-style model string (`gemini/…`, `anthropic/…`, `openai/…`). Used by
 * both CrewAI (which runs on LiteLLM) and the OpenAI Agents SDK's LitellmModel.
 */
function litellmModel(provider?: string, model?: string): string {
  const id = cleanModelId(model);
  const fam = detectFamily(provider, model);
  if (fam === "anthropic") return `anthropic/${id}`;
  if (fam === "google") return `gemini/${id}`;
  return `openai/${id}`;
}

/** Env var LiteLLM reads for a given family. */
function litellmEnvVar(fam: Family): string {
  if (fam === "anthropic") return "ANTHROPIC_API_KEY";
  if (fam === "google") return "GEMINI_API_KEY";
  return "OPENAI_API_KEY";
}

function agentNodes(nodes: PortableSwarmNode[]): PortableSwarmNode[] {
  return nodes.filter((n) => n.kind === "agent");
}

/** Unique, ordered list of tool ids enabled across the given agent nodes. */
function collectTools(agents: PortableSwarmNode[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const a of agents) {
    for (const t of a.enabledTools || []) {
      if (!seen.has(t)) {
        seen.add(t);
        out.push(t);
      }
    }
  }
  return out;
}

/**
 * Topological order of agent nodes (Kahn), over BRIDGED edges so a dependency
 * that runs through a condition/approval/function node still orders correctly.
 * Falls back to input order on cycles.
 */
function topoAgents(nodes: PortableSwarmNode[], edges: PortableSwarmEdge[]): PortableSwarmNode[] {
  const agents = agentNodes(nodes);
  const bridged = bridgeAgentEdges(nodes, edges);
  const indeg = new Map<string, number>();
  agents.forEach((a) => indeg.set(a.id, 0));
  for (const e of bridged) indeg.set(e.target, (indeg.get(e.target) ?? 0) + 1);
  const queue = agents.filter((a) => (indeg.get(a.id) ?? 0) === 0).map((a) => a.id);
  const ordered: string[] = [];
  while (queue.length) {
    const id = queue.shift()!;
    ordered.push(id);
    for (const e of bridged) {
      if (e.source !== id) continue;
      const d = (indeg.get(e.target) ?? 0) - 1;
      indeg.set(e.target, d);
      if (d === 0) queue.push(e.target);
    }
  }
  // Append any nodes left out by a cycle, preserving original order.
  for (const a of agents) if (!ordered.includes(a.id)) ordered.push(a.id);
  return ordered.map((id) => agents.find((a) => a.id === id)!);
}

/**
 * Agents `nodeId` hands off to, tunnelling through node kinds this framework
 * can't express — a direct-only lookup silently dropped every handoff whose
 * path crossed a condition/approval/function node.
 */
function downstreamAgents(
  nodeId: string,
  nodes: PortableSwarmNode[],
  edges: PortableSwarmEdge[],
): { node: PortableSwarmNode; via: string[]; paths: number }[] {
  return bridgeAgentEdges(nodes, edges)
    .filter((e) => e.source === nodeId)
    .map((e) => ({ node: nodes.find((n) => n.id === e.target)!, via: e.via, paths: e.paths }))
    .filter((x) => Boolean(x.node));
}

function controlFlowNote(nodes: PortableSwarmNode[]): string[] {
  const kinds = ["condition", "loop", "approval", "evaluate", "function", "a2a_remote"];
  const present = nodes.filter((n) => kinds.includes(n.kind));
  if (!present.length) return [];
  const lines: string[] = [];
  lines.push(`# NOTE: this swarm also contains control-flow nodes that do not map`);
  lines.push(`# directly onto this framework. Wire them up manually:`);
  for (const n of present) {
    lines.push(`#   - ${n.kind}: "${n.label}"`);
  }
  return lines;
}

/* ────────────────────────────────────────────────────────────────────────
   CrewAI (Python)
   ──────────────────────────────────────────────────────────────────────── */

export function buildCrewAISwarm(swarm: PortableSwarm): string {
  const { nodes, edges } = swarm;
  const ordered = topoAgents(nodes, edges);
  const tools = collectTools(ordered);
  const anyTools = tools.length > 0;
  const L: string[] = [];

  L.push(`"""CrewAI swarm: ${swarm.name}`);
  L.push(`Generated by AgentSwarm — https://agentswarms.fyi`);
  L.push(``);
  for (const n of FIDELITY_NOTE) L.push(n);
  L.push(``);
  L.push(`!! ${MODEL_ID_WARNING}`);
  L.push(``);
  L.push(`Install:`);
  L.push(`    pip install crewai`);
  L.push(``);
  L.push(`Run:`);
  L.push(`    # Set the API key matching your model providers, e.g.:`);
  L.push(`    #   export OPENAI_API_KEY=...   (or ANTHROPIC_API_KEY / GEMINI_API_KEY)`);
  L.push(`    python ${safePy(swarm.name)}_crewai.py`);
  L.push(`"""`);
  L.push(`from crewai import Agent, Task, Crew, Process`);
  if (anyTools) L.push(`from crewai.tools import tool`);
  L.push(``);

  if (!ordered.length) {
    L.push(`# This swarm has no agent nodes to export.`);
    return L.join("\n");
  }

  // Tool stubs (shared; referenced by the agents that enable them)
  if (anyTools) {
    L.push(`# ── Tools (stubs — implement each body; hosted tools are not portable) ──`);
    for (const t of tools) {
      const fn = safePy(t);
      L.push(`@tool("${t}")`);
      L.push(`def ${fn}(query: str) -> str:`);
      L.push(`    """${toolDescription(t)}"""`);
      L.push(`    return f"TODO: implement ${fn} for: {query}"`);
      L.push(``);
    }
  }

  // Agents
  L.push(`# ── Agents ──`);
  for (const a of ordered) {
    const v = `agent_${safePy(a.id)}`;
    const goal = JSON.stringify(
      swarm.description || `Carry out the "${a.label}" step of the swarm.`,
    );
    const backstory = JSON.stringify(a.systemPrompt || `You are ${a.label}, an AI agent.`);
    const agentTools = (a.enabledTools || []).map((t) => safePy(t));
    L.push(`${v} = Agent(`);
    L.push(`    role=${JSON.stringify(a.label)},`);
    L.push(`    goal=${goal},`);
    L.push(`    backstory=${backstory},`);
    L.push(`    llm=${JSON.stringify(litellmModel(a.provider, a.model))},`);
    if (agentTools.length) L.push(`    tools=[${agentTools.join(", ")}],`);
    L.push(`    verbose=True,`);
    L.push(`    allow_delegation=False,`);
    L.push(`)`);
    L.push(``);
  }

  // Tasks — one per agent, chained via `context` to upstream tasks (topo order).
  L.push(`# ── Tasks (sequential; each receives upstream task outputs as context) ──`);
  const taskVar = (id: string) => `task_${safePy(id)}`;
  const bridged = bridgeAgentEdges(nodes, edges);
  for (const a of ordered) {
    // Bridged upstream: a task fed through a condition/approval node still
    // needs its predecessor's output as context. Resolving raw edges here
    // dropped those, because the source was a node kind CrewAI has no task for.
    const upstream = bridged.filter((e) => e.target === a.id);
    const ctx = upstream.map((u) => taskVar(u.source));
    for (const u of upstream) {
      if (u.via.length) {
        const from = ordered.find((o) => o.id === u.source)?.label ?? u.source;
        L.push(`# ${from} → ${a.label}${viaSuffix(u.via, u.paths)}`);
      }
    }
    L.push(`${taskVar(a.id)} = Task(`);
    L.push(
      `    description=${JSON.stringify(`${a.systemPrompt || a.label}\n\nWork on the swarm input: {input}`)},`,
    );
    L.push(`    expected_output=${JSON.stringify(`The result of the "${a.label}" step.`)},`);
    L.push(`    agent=agent_${safePy(a.id)},`);
    if (ctx.length) L.push(`    context=[${ctx.join(", ")}],`);
    L.push(`)`);
    L.push(``);
  }

  const cf = controlFlowNote(nodes);
  if (cf.length) {
    L.push(...cf);
    L.push(``);
  }

  // Crew
  L.push(`# ── Crew ──`);
  L.push(`crew = Crew(`);
  L.push(`    agents=[${ordered.map((a) => `agent_${safePy(a.id)}`).join(", ")}],`);
  L.push(`    tasks=[${ordered.map((a) => taskVar(a.id)).join(", ")}],`);
  L.push(`    process=Process.sequential,`);
  L.push(`    verbose=True,`);
  L.push(`)`);
  L.push(``);
  L.push(`if __name__ == "__main__":`);
  L.push(`    result = crew.kickoff(inputs={"input": "Hello, run the swarm!"})`);
  L.push(`    print(result)`);

  return L.join("\n");
}

/* ────────────────────────────────────────────────────────────────────────
   OpenAI Agents SDK (Python)
   ──────────────────────────────────────────────────────────────────────── */

export function buildOpenAIAgentsSwarm(swarm: PortableSwarm): string {
  const { nodes, edges } = swarm;
  const ordered = topoAgents(nodes, edges);
  const tools = collectTools(ordered);
  const anyTools = tools.length > 0;
  // Non-OpenAI models can't hit the OpenAI API directly — they need the SDK's
  // LiteLLM bridge. Detect whether any agent uses a non-OpenAI family.
  const families = new Map<string, Family>();
  for (const a of ordered) families.set(a.id, detectFamily(a.provider, a.model));
  const needLitellm = [...families.values()].some((f) => f !== "openai");
  const L: string[] = [];

  L.push(`"""OpenAI Agents SDK swarm: ${swarm.name}`);
  L.push(`Generated by AgentSwarm — https://agentswarms.fyi`);
  L.push(``);
  for (const n of FIDELITY_NOTE) L.push(n);
  L.push(``);
  L.push(`!! ${MODEL_ID_WARNING}`);
  if (needLitellm) {
    L.push(``);
    L.push(`Non-OpenAI models route through the SDK's LiteLLM bridge (LitellmModel).`);
    L.push(`Set the matching provider key (e.g. GEMINI_API_KEY / ANTHROPIC_API_KEY).`);
  }
  L.push(``);
  L.push(`Install:`);
  L.push(`    pip install "openai-agents${needLitellm ? "[litellm]" : ""}"`);
  L.push(``);
  L.push(`Run:`);
  L.push(
    `    export OPENAI_API_KEY=...   ${needLitellm ? "# + provider keys for non-OpenAI models" : ""}`,
  );
  L.push(`    python ${safePy(swarm.name)}_openai_agents.py`);
  L.push(``);
  L.push(`Edges between agents become handoffs. The first agent with no`);
  L.push(`upstream agent is the entrypoint.`);
  L.push(`"""`);
  L.push(`import asyncio`);
  if (needLitellm) L.push(`import os`);
  L.push(`from agents import Agent, Runner${anyTools ? ", function_tool" : ""}`);
  if (needLitellm) L.push(`from agents.extensions.models.litellm_model import LitellmModel`);
  L.push(``);

  if (!ordered.length) {
    L.push(`# This swarm has no agent nodes to export.`);
    return L.join("\n");
  }

  // Tool stubs (shared; referenced by the agents that enable them)
  if (anyTools) {
    L.push(`# ── Tools (stubs — implement each body; hosted tools are not portable) ──`);
    for (const t of tools) {
      const fn = safePy(t);
      L.push(`@function_tool`);
      L.push(`def ${fn}(query: str) -> str:`);
      L.push(`    """${toolDescription(t)}"""`);
      L.push(`    return f"TODO: implement ${fn} for: {query}"`);
      L.push(``);
    }
  }

  // Define all agents first (no handoffs yet) so we can wire references freely
  // without worrying about definition order or cycles.
  L.push(`# ── Agents ──`);
  for (const a of ordered) {
    const v = `agent_${safePy(a.id)}`;
    const instr = JSON.stringify(a.systemPrompt || `You are ${a.label}, an AI agent.`);
    const fam = families.get(a.id) || "openai";
    const agentTools = (a.enabledTools || []).map((t) => safePy(t));
    // OpenAI-family models pass as a plain string; others go through LiteLLM.
    const modelExpr =
      fam === "openai"
        ? JSON.stringify(cleanModelId(a.model))
        : `LitellmModel(model=${JSON.stringify(litellmModel(a.provider, a.model))}, api_key=os.environ.get(${JSON.stringify(litellmEnvVar(fam))}))`;
    L.push(`${v} = Agent(`);
    L.push(`    name=${JSON.stringify(a.label)},`);
    L.push(`    instructions=${instr},`);
    L.push(`    model=${modelExpr},`);
    if (agentTools.length) L.push(`    tools=[${agentTools.join(", ")}],`);
    L.push(`)`);
    L.push(``);
  }

  // Wire handoffs after construction (handles forward refs + cycles).
  const withHandoffs = ordered.filter((a) => downstreamAgents(a.id, nodes, edges).length > 0);
  if (withHandoffs.length) {
    L.push(`# ── Handoffs (from graph edges) ──`);
    for (const a of withHandoffs) {
      const downstream = downstreamAgents(a.id, nodes, edges);
      const bridged = downstream.filter((d) => d.via.length);
      for (const d of bridged) {
        L.push(`# ${a.label} → ${d.node.label}${viaSuffix(d.via, d.paths)}`);
      }
      const targets = downstream.map((d) => `agent_${safePy(d.node.id)}`);
      L.push(`agent_${safePy(a.id)}.handoffs = [${targets.join(", ")}]`);
    }
    L.push(``);
  }

  const cf = controlFlowNote(nodes);
  if (cf.length) {
    L.push(...cf);
    L.push(``);
  }

  // Entry agent = first in topological order (no upstream agent).
  const entry = ordered[0];
  L.push(`# ── Run ──`);
  L.push(`async def main():`);
  L.push(`    result = await Runner.run(agent_${safePy(entry.id)}, "Hello, run the swarm!")`);
  L.push(`    print(result.final_output)`);
  L.push(``);
  L.push(`if __name__ == "__main__":`);
  L.push(`    asyncio.run(main())`);

  return L.join("\n");
}

/* ────────────────────────────────────────────────────────────────────────
   Download helpers
   ──────────────────────────────────────────────────────────────────────── */

function safeFileName(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "swarm"
  );
}

export function downloadSwarmAsCrewAI(swarm: PortableSwarm) {
  downloadFile(`${safeFileName(swarm.name)}_crewai.py`, buildCrewAISwarm(swarm), "text/x-python");
}

export function downloadSwarmAsOpenAIAgents(swarm: PortableSwarm) {
  downloadFile(
    `${safeFileName(swarm.name)}_openai_agents.py`,
    buildOpenAIAgentsSwarm(swarm),
    "text/x-python",
  );
}
