#!/usr/bin/env bash
# PHASE 4 — assemble the two-tier release notes. Deterministic stitching of the
# synthesized sections + a synth-written intro (highlights/breaking/upgrade) +
# a deterministically rendered internal appendix. One consolidated v4 doc.
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"; source "$HERE/config.sh"; source "$HERE/lib.sh"
mkdir -p "$(dirname "$OUT_NOTES")" "$RAW_DIR"
commits=$(git -C "$REPO" rev-list --count "$BASELINE_TAG..$TARGET_REF" 2>/dev/null)

# 1) intro via synth model (fed the section headers only — small, safe)
pf="$RAW_DIR/intro.prompt"; raw="$RAW_DIR/intro.raw"; intro="$WORK/intro.md"
{
cat <<EOF
## Role
You are writing the top of the $VERSION release notes for the OpenCode Spec-Kit framework. You have no tools; reply with markdown only.

## Context
$commits commits shipped between $BASELINE_TAG and $VERSION. The full per-section detail follows in the document; below are the section drafts:
<<<SECTIONS
EOF
for s in "$OUT_SECTIONS"/*.md; do [ -f "$s" ] && { echo; cat "$s"; }; done
cat <<EOF
SECTIONS

## Action
Write the release-notes opening: a 2-3 sentence summary, then "## Highlights" with 5-8 headline bullets (the biggest user-facing wins across all sections), then "## Breaking changes" (list any breaking items; if none say "None."), then "## Upgrade notes" (1-3 practical bullets). Ground everything in the sections; invent nothing.

## Format
Reply with ONLY markdown: the summary paragraph, then the three headed subsections above. Do NOT repeat the full section detail.
EOF
} > "$pf"
log "assemble: intro"
synth_dispatch "$pf" "$raw"; extract_markdown "$raw" "$intro"

# 2) stitch the final document deterministically
{
  echo "# $VERSION — Release Notes"
  echo
  echo "> $commits commits since \`$BASELINE_TAG\`. Generated by the cheap-model release-notes pipeline."
  echo
  cat "$intro"
  echo; echo "---"; echo
  echo "## What changed"; echo
  for s in "$OUT_SECTIONS"/*.md; do [ -f "$s" ] && { cat "$s"; echo; }; done
  echo "---"; echo
  # 3) internal appendix — rendered deterministically from internal fragments
  echo "## Appendix: Internal & developer changes"; echo
  python3 - "$WORK/buckets/internal.json" <<'PY'
import json,sys,collections
try: items=json.load(open(sys.argv[1]))
except Exception: items=[]
by=collections.defaultdict(list)
for r in items: by[r.get('section','misc')].append(r)
for track in sorted(by):
    print(f"#### {track}")
    for r in by[track]:
        t=r.get('title','').strip()
        b=r.get('bullets') or []
        print(f"- **{t}** — {b[0] if b else ''}".rstrip())
    print()
PY
} > "$OUT_NOTES"
log "PHASE4 assembled -> $OUT_NOTES ($(wc -l <"$OUT_NOTES") lines)"
mark_done phase4
