#!/usr/bin/env bash
# Build a changelog SUMMARY per spec folder, CATEGORIZED per skill. DeepSeek-Flash
# writes each folder's summary (read-only; parent writes files). Folders are
# grouped by track (skill), each track chunked to fit the model window; chunks
# run in parallel, then assembled in skill order.
# Usage: dr-by-skill.sh [assemble]   (no arg = dispatch+assemble; 'assemble' = re-stitch only)
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"; source "$HERE/config.sh"; source "$HERE/lib.sh"
OUT="$SPEC/003-deep-research-synthesis/changelog-by-skill.md"
CHUNKD="$WORK/by-skill"; mkdir -p "$CHUNKD" "$RAW_DIR" "$FAIL_DIR"
CHUNK="${CHUNK:-6}"

# skill display order + titles
TRACK_ORDER="system-speckit system-deep-loop cli-external-orchestration sk-doc sk-design sk-code sk-git sk-prompt mcp-tooling hooks system-skill-advisor agents"
title_for(){ case "$1" in
  cli-external-orchestration) echo "External CLI Orchestration";; system-deep-loop) echo "Deep Loop";;
  system-speckit) echo "Spec Kit & Memory";; sk-doc) echo "Documentation (sk-doc)";;
  sk-code) echo "Code (sk-code)";; sk-git) echo "Git (sk-git)";; sk-design) echo "Design (sk-design)";;
  sk-prompt) echo "Prompt (sk-prompt)";; mcp-tooling) echo "MCP Tooling";; hooks) echo "Hooks & Runtime";;
  system-skill-advisor) echo "Skill Advisor";; agents) echo "Agents";; *) echo "$1";; esac; }

slugs_for_track(){ awk -F'\t' -v t="$1" '$2==t{n=split($4,a,"/"); f=a[n]; sub(/\.md$/,"",f); print f}' "$MANIFEST"; }

# ---- build chunk jobs: <ord>__<track>__<partNN> = space-joined slugs ----
build_jobs(){
  : > "$CHUNKD/jobs.tsv"; ord=0
  for tr in $TRACK_ORDER; do
    ord=$((ord+1)); part=0; buf=""
    for s in $(slugs_for_track "$tr"); do
      buf="$buf $s"
      if [ "$(echo $buf | wc -w)" -ge "$CHUNK" ]; then
        part=$((part+1)); printf '%02d__%s__%02d\t%s\n' "$ord" "$tr" "$part" "$(echo $buf|xargs)" >> "$CHUNKD/jobs.tsv"; buf=""
      fi
    done
    [ -n "$(echo $buf|xargs)" ] && { part=$((part+1)); printf '%02d__%s__%02d\t%s\n' "$ord" "$tr" "$part" "$(echo $buf|xargs)" >> "$CHUNKD/jobs.tsv"; }
  done
}

dispatch_chunk(){  # arg: job-id ; reads slugs from jobs.tsv
  local jid="$1"; local slugs; slugs=$(awk -F'\t' -v j="$jid" '$1==j{print $2}' "$CHUNKD/jobs.tsv")
  local out="$CHUNKD/$jid.md"; [ -s "$out" ] && { echo "SKIP $jid"; return 0; }
  local pf="$RAW_DIR/skill-$jid.prompt" raw="$RAW_DIR/skill-$jid.raw"
  {
cat <<'EOF'
## Role
You are writing the v4.0.0.0 changelog for "OpenCode Spec-Kit". For EACH spec folder below, write a concise changelog SUMMARY entry. You have no tools; reply with markdown only.

## Context
Each folder shipped in the v3.6.0.0 -> v4.0.0.0 cycle. Ignore internal noise (YAML frontmatter, ANCHOR markers, CI names, session metadata, phase numbers).

EOF
for s in $slugs; do
  pkt=$(sed -n '1s/^# PACKET: //p' "$SRC_DIR/$s.md" | sed -E 's/ \(.*//; s#^specs/##')
  echo "<<<FOLDER id=\"$pkt\""; cat "$SRC_DIR/$s.md"; echo "FOLDER"; echo
done
cat <<'EOF'
## Action
For EACH folder, output exactly:

#### <folder id> — <short title, <= 8 words>
A 2-4 sentence summary of what changed and why it matters to a framework user. Ground it in that folder's source; invent nothing. If breaking, end with "**Breaking:** ...". If purely internal tooling, say so in one clause.

## Format
Reply with ONLY the `####` blocks, one per folder, in the given order, using each folder's exact id after the em dash heading. No preamble, no summary.
EOF
  } > "$pf"
  dispatch_opencode "$EXTRACT_MODEL" "$pf" "$raw"
  if extract_markdown "$raw" "$out" && [ -s "$out" ]; then echo "OK $jid"; else echo "FAIL $jid"; rm -f "$out"; fi
}
export -f dispatch_chunk title_for slugs_for_track dispatch_opencode extract_markdown log
export CHUNKD MANIFEST SRC_DIR RAW_DIR FAIL_DIR EXTRACT_MODEL REPO DISPATCH_TIMEOUT LOG

assemble(){
  { echo "# v4.0.0.0 Changelog — by skill"; echo
    echo "> Per-spec-folder changelog summaries, categorized by skill. $(grep -c . "$MANIFEST") folders across the v3.6.0.0 -> v4.0.0.0 window. Generated by DeepSeek V4 Flash."; echo
    ord=0
    for tr in $TRACK_ORDER; do
      ord=$((ord+1)); has=$(ls "$CHUNKD"/$(printf '%02d' $ord)__${tr}__*.md 2>/dev/null | wc -l | tr -d ' ')
      [ "$has" -eq 0 ] && continue
      echo "---"; echo; echo "## $(title_for "$tr")"; echo
      for f in $(ls "$CHUNKD"/$(printf '%02d' $ord)__${tr}__*.md 2>/dev/null | sort); do cat "$f"; echo; done
    done
  } > "$OUT"
  echo "assembled -> $OUT ($(wc -l <"$OUT") lines, $(grep -c '^#### ' "$OUT") folder entries)"
}

if [ "${1:-}" = "assemble" ]; then assemble; exit 0; fi
build_jobs
jobs=$(cut -f1 "$CHUNKD/jobs.tsv"); n=$(echo "$jobs" | grep -c .)
log "by-skill: $n chunks (CHUNK=$CHUNK), concurrency 5"
echo "$jobs" | xargs -P5 -I{} bash -c 'dispatch_chunk "$@"' _ {} | tee -a "$LOG"
assemble
