/**
 * Raw database row from the `memory_index` table.
 * Column names match the production schema exactly (snake_case).
 *
 * Source of truth: vector-index-impl.js CREATE TABLE memory_index
 */
export interface MemoryDbRow {
    id: number;
    spec_folder: string;
    file_path: string;
    anchor_id: string | null;
    title: string | null;
    trigger_phrases: string | null;
    importance_weight: number;
    created_at: string;
    updated_at: string;
    embedding_model: string | null;
    embedding_generated_at: string | null;
    embedding_status: string;
    retry_count: number;
    last_retry_at: string | null;
    failure_reason: string | null;
    base_importance: number;
    decay_half_life_days: number;
    is_pinned: number;
    access_count: number;
    last_accessed: number;
    importance_tier: string;
    session_id: string | null;
    context_type: string;
    channel: string;
    content_hash: string | null;
    expires_at: string | null;
    confidence: number;
    validation_count: number;
    stability: number;
    difficulty: number;
    last_review: string | null;
    review_count: number;
    file_mtime_ms: number | null;
    document_type: string;
    spec_level: number | null;
}
/**
 * Application-level memory object (camelCase).
 * This is what handler code should work with after normalization.
 */
export interface Memory {
    id: number;
    specFolder: string;
    filePath: string;
    anchorId: string | null;
    title: string | null;
    triggerPhrases: string | null;
    importanceWeight: number;
    createdAt: string;
    updatedAt: string;
    embeddingModel: string | null;
    embeddingGeneratedAt: string | null;
    embeddingStatus: string;
    retryCount: number;
    lastRetryAt: string | null;
    failureReason: string | null;
    baseImportance: number;
    decayHalfLifeDays: number;
    isPinned: boolean;
    accessCount: number;
    lastAccessed: number;
    importanceTier: string;
    sessionId: string | null;
    contextType: string;
    channel: string;
    contentHash: string | null;
    expiresAt: string | null;
    confidence: number;
    validationCount: number;
    stability: number;
    difficulty: number;
    lastReview: string | null;
    reviewCount: number;
    fileMtimeMs: number | null;
    documentType: string;
    specLevel: number | null;
}
/**
 * Convert a raw database row to the application-level Memory type.
 * This is the ONLY place where snake_case → camelCase mapping lives.
 */
export declare function dbRowToMemory(row: MemoryDbRow): Memory;
/**
 * Convert an application-level Memory to a partial DB row for INSERT/UPDATE.
 * Omits `id` (auto-generated by DB).
 * Only includes fields that are present on the Memory object.
 */
export declare function memoryToDbRow(memory: Partial<Memory>): Partial<MemoryDbRow>;
/**
 * Convert a partial DB row (e.g., from a SELECT with fewer columns)
 * to a partial Memory. Useful for search results that don't fetch all columns.
 */
export declare function partialDbRowToMemory(row: Partial<MemoryDbRow> & {
    id: number;
}): Partial<Memory> & {
    id: number;
};
