// ╔══════════════════════════════════════════════════════════════════════════╗
// ║ Sync Codex Prompts                                                       ║
// ╚══════════════════════════════════════════════════════════════════════════╝

'use strict';

const fs = require('node:fs');
const path = require('node:path');

const REPO_ROOT = path.resolve(__dirname, '../../../../..');
const SOURCE_DIR = path.join(REPO_ROOT, '.opencode', 'commands');
const OUTPUT_DIR = path.join(REPO_ROOT, '.codex', 'prompts');
const EXCLUDED_DIRECTORIES = new Set(['assets', 'scripts', 'fixtures']);

function parseArguments(argv) {
  if (argv.length === 0) {
    return { check: false };
  }
  if (argv.length === 1 && argv[0] === '--check') {
    return { check: true };
  }
  throw new Error('Usage: node sync-prompts.cjs [--check]');
}

function listCommandFiles(directory) {
  if (!fs.existsSync(directory)) {
    return [];
  }

  const relativePaths = [];
  const walk = (current) => {
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const absolute = path.join(current, entry.name);
      if (entry.isDirectory()) {
        if (!EXCLUDED_DIRECTORIES.has(entry.name)) {
          walk(absolute);
        }
        continue;
      }
      if (!entry.isFile() || !entry.name.endsWith('.md')) {
        continue;
      }
      if (entry.name === 'README.md' || entry.name.endsWith('.contract.md')) {
        continue;
      }
      relativePaths.push(path.relative(SOURCE_DIR, absolute).split(path.sep).join('/'));
    }
  };

  walk(directory);
  return relativePaths.sort();
}

function listOutputFiles() {
  if (!fs.existsSync(OUTPUT_DIR)) {
    return [];
  }
  return fs.readdirSync(OUTPUT_DIR, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.md'))
    .map((entry) => entry.name)
    .sort();
}

function toFlatName(relativePath) {
  return relativePath.replace(/\.md$/, '').split('/').join('-');
}

function renderPrompt(relativePath) {
  const flatName = toFlatName(relativePath);

  return [
    `<!-- Generated by sync-prompts.cjs from .opencode/commands/${relativePath} — do not edit by hand. -->`,
    `# Codex entry: /${flatName}`,
    '',
    `This is the Codex runtime entry point for the \`/${flatName}\` command. The canonical, authoritative command definition lives in the OpenCode tree at:`,
    '',
    `\`.opencode/commands/${relativePath}\``,
    '',
    "Read that file in full and follow it exactly as the command's instructions. It is the single source of truth for this command's routing, assets, execution targets, and presentation. Treat everything below the frontmatter there as your operating contract.",
    '',
    "Arguments passed to this prompt are available as `$ARGUMENTS` and map to the canonical command's `$ARGUMENTS` / positional `$1`..`$N` inputs.",
    '',
    'User request: $ARGUMENTS',
    '',
  ].join('\n');
}

function buildExpectedOutputs() {
  const sourceFiles = listCommandFiles(SOURCE_DIR);
  if (sourceFiles.length === 0) {
    throw new Error(`No canonical commands found in ${SOURCE_DIR}`);
  }

  return new Map(sourceFiles.map((relativePath) => [
    `${toFlatName(relativePath)}.md`,
    renderPrompt(relativePath),
  ]));
}

function checkOutputs(expectedOutputs) {
  const actualFiles = new Set(listOutputFiles());
  const drift = [];

  for (const [outputFile, expected] of expectedOutputs) {
    const outputPath = path.join(OUTPUT_DIR, outputFile);
    if (!actualFiles.has(outputFile)) {
      drift.push(`MISSING ${path.relative(REPO_ROOT, outputPath)}`);
      continue;
    }
    actualFiles.delete(outputFile);
    if (fs.readFileSync(outputPath, 'utf8') !== expected) {
      drift.push(`STALE ${path.relative(REPO_ROOT, outputPath)}`);
    }
  }

  for (const outputFile of [...actualFiles].sort()) {
    drift.push(`EXTRA ${path.relative(REPO_ROOT, path.join(OUTPUT_DIR, outputFile))}`);
  }

  if (drift.length > 0) {
    console.error('[codex-prompt-sync] Drift detected:');
    for (const item of drift) {
      console.error(`[codex-prompt-sync] ${item}`);
    }
    return false;
  }

  console.log(`[codex-prompt-sync] PASS: ${expectedOutputs.size} prompts are in sync.`);
  return true;
}

function writeOutputs(expectedOutputs) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  const expectedFiles = new Set(expectedOutputs.keys());

  for (const outputFile of listOutputFiles()) {
    if (!expectedFiles.has(outputFile)) {
      fs.unlinkSync(path.join(OUTPUT_DIR, outputFile));
    }
  }

  let changed = 0;
  for (const [outputFile, expected] of expectedOutputs) {
    const outputPath = path.join(OUTPUT_DIR, outputFile);
    // A pre-existing symlink at a generated output path would redirect the write
    // outside the intended output root; refuse to follow it instead of writing through.
    let stat = null;
    try {
      stat = fs.lstatSync(outputPath);
    } catch (err) {
      if (err.code !== 'ENOENT') throw err;
    }
    if (stat && stat.isSymbolicLink()) {
      throw new Error(`refusing to write through a pre-existing symlink at ${outputPath}`);
    }
    const actual = stat ? fs.readFileSync(outputPath, 'utf8') : null;
    if (actual !== expected) {
      fs.writeFileSync(outputPath, expected, 'utf8');
      changed += 1;
    }
  }

  console.log(
    `[codex-prompt-sync] Wrote ${changed} of ${expectedOutputs.size} generated prompts.`,
  );
}

function main() {
  const options = parseArguments(process.argv.slice(2));
  const expectedOutputs = buildExpectedOutputs();
  if (options.check) {
    if (!checkOutputs(expectedOutputs)) {
      process.exitCode = 1;
    }
    return;
  }
  writeOutputs(expectedOutputs);
}

try {
  main();
} catch (error) {
  console.error(`[codex-prompt-sync] ERROR: ${error.message}`);
  process.exitCode = 1;
}
