#!/usr/bin/env bash
# Dispatches the bounded deep-research loop for this phase through the cli-pi executor.
#
# The research command's own engine is the fan-out runner, so this is the command's
# execution path with a single cli-pi lineage rather than a nested dispatch: a pi
# child that ran the command surface with --executor=cli-pi would dispatch cli-pi
# again from inside a cli-pi stack, which the shared runtime refuses by design.
set -uo pipefail

REPO=/Users/michelkerkmeester/worktrees/public/056-repo-rules-source-root-migration
PKT=specs/system-speckit/033-system-speckit-v4/041-skilled-source-root-migration/021-repo-rules-source-root-migration

TOPIC="Where does every live consumer of the rule corpus live, and what breaks when the corpus moves from the repository-root repo-rules/ to the canonical .skilled/repo-rules/ with a tracked per-entry symlink farm left at the root? Answer three questions. Q1, in-repo consumers outside specs/: which tracked files name a rule file or the rules directory as a live path, at file:line, and what changes for each, covering the 26 router rows in REPO RULES.md, the 13 rule-body backlinks to ../REPO%20RULES.md, AGENTS.md's five links, the corpus checker, the sk-doc sk-create-repo-rule skill and its manual-testing-playbook, the /create:repo-rule command and its assets, the two authored agent files, and the sk-communication benchmark generator. Q2, generators, mirrors, CI and gate inputs: which of .claude/agents, .pi/agents, .codex/agents and .hermes/skills are generated and from which authored source, which script checks each, what the workflow repo-rules-corpus.yml and .github/scripts/check-gate-inputs.sh key on, and whether the trigger index, corpus-manifest, generation-diagnostics and phrase-variants artifacts can be regenerated byte-identically. Q3, external consumers and portability: what the sibling repositories link into, and how check-repo-rules.cjs can probe .skilled/repo-rules before repo-rules while keeping its nine checks and resolving router rows by link target. Cite file:line for every claim, and mark anything you could not confirm as INFERRED rather than stating it."

cd "$REPO" || exit 2

exec node .skilled/skills/system-deep-loop/runtime/scripts/fanout-run.cjs \
  --spec-folder "$PKT" \
  --loop-type research \
  --research-topic "$TOPIC" \
  --fanout-config-json '{"executors":[{"kind":"cli-pi","model":"deepseek-v4.1-flash","label":"deepseek","iterations":3}],"concurrency":1}' \
  --base-artifact-dir "$PKT/research" \
  --convergence-threshold 0.05 \
  --convergence-mode default \
  --stop-policy max-iterations
