// Squid dstdomain allow-list rendering for notebook kernel egress.
//
// Pure module (no `.server` suffix, no imports) so the rendering and hostname
// rules can be unit-tested — `.server.ts` files are import-protected.

/** Hosts always permitted, whatever the operator configures. Without PyPI a
 *  kernel cannot `pip install` anything, which defeats the runtime's purpose. */
export const EGRESS_BASELINE = ["pypi.org", "files.pythonhosted.org"];

/**
 * Normalise one operator-entered host into a squid `dstdomain` token.
 *
 * Squid treats a leading dot as "this domain and all subdomains", which is
 * almost always what someone means when they type `github.com` — package
 * installs routinely redirect to `codeload.github.com` or a CDN subdomain, and
 * an entry without the dot would silently fail to match those.
 *
 * Returns null for anything that isn't a usable hostname, so a typo is dropped
 * rather than written into the ACL where it would be inert.
 */
export function normalizeEgressHost(raw: string): string | null {
  let h = (raw ?? "").trim().toLowerCase();
  if (!h || h.startsWith("#")) return null;

  // Tolerate pasted URLs: strip scheme, path, port, credentials.
  h = h.replace(/^[a-z][a-z0-9+.-]*:\/\//, "");
  h = h.split("/")[0];
  h = h.split("@").pop() ?? h;
  h = h.replace(/:\d+$/, "");
  // A leading dot is meaningful to squid; strip it here and re-add below so
  // "github.com" and ".github.com" normalise to the same token.
  h = h.replace(/^\.+/, "").replace(/\.+$/, "");
  if (!h) return null;

  // Wildcards are written as a leading dot in squid, not as "*".
  h = h.replace(/^\*\./, "");

  // Reject anything that isn't a plausible hostname.
  //
  // The previous test was /^[a-z0-9-]+(\.[a-z0-9-]+)+$/, which admits digits in
  // every label and so accepted IP ADDRESSES — `10.0.0.1` became the ACL entry
  // `.10.0.0.1`. squid matches dstdomain by DNS suffix, so that entry can never
  // match a request to 10.0.0.1 and sits there doing nothing. An operator who
  // allow-lists an internal address then believes egress to it is permitted
  // when it is not, which is exactly the "written into the ACL where it would
  // be inert" outcome this function's contract promises to prevent. It also
  // accepted `-lead.com` and `trail-.com`, which are not valid hostnames.
  if (h.length > 253) return null;
  const labels = h.split(".");
  if (labels.length < 2) return null;
  // RFC 1123: a label is alphanumeric, may contain inner hyphens, max 63.
  const LABEL = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/;
  if (!labels.every((l) => l.length > 0 && l.length <= 63 && LABEL.test(l))) return null;
  // An all-numeric final label means this is an address, not a domain: no real
  // TLD is numeric. This is what rejects IPv4. (IPv6 never reaches here — the
  // colon-stripping above mangles it and the label test then fails.)
  if (/^\d+$/.test(labels[labels.length - 1])) return null;

  return "." + h;
}

/**
 * Render the full squid ACL file from the operator's list.
 *
 * The baseline is unioned in and the result de-duplicated, so an operator
 * cannot lock kernels out of PyPI by clearing the field.
 */
export function renderEgressAllowlist(hosts: string[]): string {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const raw of [...EGRESS_BASELINE, ...(hosts ?? [])]) {
    const token = normalizeEgressHost(raw);
    if (!token || seen.has(token)) continue;
    seen.add(token);
    out.push(token);
  }
  return (
    "# Generated by AgentSwarms from notebook_runtime_settings.egress_allowlist.\n" +
    "# Edits here are overwritten whenever an administrator saves runtime settings —\n" +
    "# change the list under Admin → Developer runtime instead.\n" +
    "#\n" +
    "# A leading dot matches the domain and all of its subdomains.\n" +
    out.join("\n") +
    "\n"
  );
}
