#!/bin/zsh
# Two-executor deep research over the memory-decommission programme, review angle:
# what did the landing (052), the runtime rename (053) and the debt fixes (054) miss?
cd /Users/michelkerkmeester/worktrees/public/044-zvec-grep-integration
TOPIC='Review-angle research over the memory-database decommission programme in this repository: what did it miss? Start by reading, in order, specs/system-speckit/052-memory-decommission-landing/goal.md (decisions D1-D9 and the full LOG), specs/system-speckit/053-spec-kit-runtime-rename/implementation-summary.md, specs/system-speckit/054-decommission-debt-fixes/spec.md and tasks.md, and the review reports under specs/system-speckit/053-spec-kit-runtime-rename/review/lineages/*/review-report.md. Then hunt for residue, drift and debt the loops did not catch. Angles to rotate across iterations: (1) live code or config that still serves or describes a retired surface (memory database, memory MCP tools, spec-memory launcher, zvec lane, system-plugins, mcp-server identity of .opencode/skills/system-spec-kit/runtime); (2) registrations, symlinks, hook configs, CI workflows and doctor assets that were dropped or left dangling by the sweeps, like the eleven session-lifecycle registrations restored at commit 273767431d; (3) dependencies without an importer and importers without a dependency across the system-spec-kit workspace (shared, scripts, runtime); (4) tests that pass only because they test a surface that no longer exists, or that were weakened rather than fixed; (5) documentation that claims a behavior the code no longer has, across .opencode/skills/system-spec-kit/**, .opencode/install-guides/**, README.md, AGENTS.md and the runtime mirrors .claude .codex .cursor .devin .pi; (6) the trigger index, ripgrep retrieval lane and continuity writer as the successors: gaps in what they cover versus what the retired memory surface covered; (7) gates that can pass while lying (freshness stamps, generated metadata, routing guard, validate.sh) after these changes. Reading budget: read files directly, never expand a directory with a wildcard, never read node_modules, dist, benchmark, changelog, z_archive, manual-testing-playbook, feature-catalog, package-lock.json or any trigger-index.json; prefer rg over broad reads and cite file:line for every finding. Record each finding with severity P0/P1/P2, evidence, and the smallest fix; distinguish confirmed from inferred.'
exec node .opencode/skills/system-deep-loop/runtime/scripts/fanout-run.cjs \
  --spec-folder .opencode/specs/system-speckit/054-decommission-debt-fixes \
  --loop-type research \
  --research-topic "$TOPIC" \
  --fanout-config-json '{"executors":[{"label":"luna-max-research","kind":"cli-codex","model":"gpt-5.6-luna","reasoningEffort":"max","serviceTier":"fast","timeoutSeconds":3600,"iterations":20},{"label":"grok-xhigh-research","kind":"cli-cursor","model":"cursor-grok-4.6-xhigh-fast","timeoutSeconds":3600,"iterations":20}],"concurrency":2}' \
  --base-artifact-dir .opencode/specs/system-speckit/054-decommission-debt-fixes/research \
  --convergence-threshold 3 --stop-policy max-iterations
