#!/usr/bin/env node
'use strict';
/**
 * Manual authoring swarm for the deep-loop recommendations implementation-planning tree.
 *
 * Dispatches one agent per phase-folder in the work-list, workspace-write,
 * each mirroring a real validated phase leaf as its structural template.
 * After an agent returns, the driver deterministically
 * generates description.json + graph-metadata.json and runs strict validation
 * on that folder, recording pass/fail. Operator-authorized parallel dispatch
 * (rule-15 swarm exception); concurrency-capped to be gentle on the shared OAuth.
 *
 * Usage: node author-swarm.cjs --wave <N> [--concurrency <k>] [--executor codex|opencode|fallback] [--only <id[,id]>] [--dry-run]
 */
const fs = require('fs');
const path = require('path');
const { spawn, spawnSync } = require('child_process');

const ROOT = '/Users/michelkerkmeester/MEGA/Development/Code_Environment/Public';
const PACKET_ROOT = path.join(ROOT, '.opencode/specs/system-deep-loop/065-deep-loop-innovation');
const SCRATCH = path.join(PACKET_ROOT, 'scratch');
const WORKLIST = path.join(SCRATCH, 'author-worklist.json');
const LOGDIR = path.join(SCRATCH, 'swarm-logs');
const RESULTS = path.join(SCRATCH, 'swarm-results.jsonl');

// Two executors. Primary cli-codex (SOL): preferred authoring quality, but shares one ChatGPT
// OAuth that gets contended/killed under load from concurrent sessions. Fallback cli-opencode
// (LUNA): the paid OpenAI API — a separate credential that keeps working when codex errors out.
// Operator policy: codex first, opencode when codex errors. The --executor flag in main()
// overrides EXECUTOR_CHAIN: 'fallback' (default) tries both; 'codex'/'opencode' force one lane.
const CODEX = { kind: 'codex', model: 'gpt-5.6-sol', effort: 'high' };
const OPENCODE = { kind: 'opencode', model: 'openai/gpt-5.6-luna-fast', variant: 'xhigh' };
let EXECUTOR_CHAIN = [CODEX, OPENCODE];
const TIMEOUT_MS = 1500 * 1000; // 25 min per agent (author + optional self-validate)

const GEN_DESC = path.join(ROOT, '.opencode/skills/system-spec-kit/scripts/dist/spec-folder/generate-description.js');
const BACKFILL = path.join(ROOT, '.opencode/skills/system-spec-kit/scripts/dist/graph/backfill-graph-metadata.js');
const VALIDATE = path.join(ROOT, '.opencode/skills/system-spec-kit/scripts/spec/validate.sh');

function nowStamp() { return new Date().toISOString(); }
function loadJSON(p, f) { try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return f; } }

// ---------- brief assembly (the quality crux) ----------
function buildParentBrief(item) {
  const refs = (item.research_refs || []).map((r) => `  - ${r}`).join('\n');
  const rows = (item.children || [])
    .map((c) => `| ${c.slug.slice(0, 3)} | \`${c.slug}/\` | ${c.focus} | ${c.status || 'Planned'} |`)
    .join('\n');
  return [
    `You are a principal engineer authoring ONE spec-kit PHASE-PARENT spec. This is REAL authoring — you WILL create a file. Repo root is the current working directory.`,
    ``,
    `GATE-3 PRE-RESOLVED: your target spec folder is pre-approved — do NOT ask the spec-folder question.`,
    `TARGET FOLDER (create files ONLY here): ${item.folder}`,
    `SCOPE LOCK [HARD]: create/modify files ONLY inside that folder. Touch nothing else in the repo. Do NOT create or edit the child folders — other agents own those.`,
    ``,
    `## Author EXACTLY ONE file: spec.md (lean phase-parent form)`,
    `A phase parent carries ONLY the lean trio {spec.md, description.json, graph-metadata.json}; the last two are generated by tooling after you finish. So you author spec.md ONLY. Do NOT write plan.md, tasks.md, or checklist.md — the heavy docs live in the children.`,
    ``,
    `## MIRROR this real phase-parent example EXACTLY (structural mold)`,
    `Read its spec.md: ${item.template}/spec.md`,
    `Copy its structure precisely: the YAML frontmatter shape; the <!-- SPECKIT_TEMPLATE_SOURCE -->, <!-- SPECKIT_LEVEL -->, and the "<!-- CONTENT DISCIPLINE: PHASE PARENT ... -->" marker comment; and its exact section set — METADATA (with a Predecessor / Successor / Handoff Criteria row), PROBLEM & PURPOSE, and a PHASE DOCUMENTATION MAP table inside <!-- ANCHOR:phase-map -->…<!-- /ANCHOR:phase-map -->. Replace the example's CONTENT with your phase's; keep its FORM. Root purpose and child map ONLY — no mechanics (those live in the children).`,
    ``,
    `## Read for context`,
    `  - ${path.join(PACKET_ROOT, 'spec.md')}  (the parent program plan — invariants, success criteria, phase map)`,
    `  - ${path.join(PACKET_ROOT, 'manifest/phase-tree.json')}  (this phase's outcome + depends_on + siblings)`,
    refs ? `  - Research inputs:\n${refs}` : '',
    ``,
    `## Your phase (parent)`,
    `Title: ${item.title}`,
    `Status: ${item.status}`,
    `Predecessor: ${item.predecessor || '(none)'}`,
    `Successor: ${item.successor || '(none)'}`,
    `Handoff Criteria: ${item.handoff_criteria || ''}`,
    `Outcome: ${item.outcome}`,
    ``,
    `PROBLEM & PURPOSE should explain, grounded in the cited files, why this phase exists and what it hands to its successor. Then fill the PHASE DOCUMENTATION MAP with EXACTLY these child rows (do not invent others):`,
    ``,
    `| Phase | Folder | Focus | Status |`,
    `|-------|--------|-------|--------|`,
    rows,
    ``,
    `Content brief (extra context):`,
    item.content_brief,
    ``,
    `## Spec-kit rules you MUST honor (validated)`,
    `- Frontmatter: title, description, trigger_phrases, importance_tier (low|medium|high|critical — use "critical" only for the keystone), contextType "planning", parent "system-deep-loop/065-deep-loop-innovation", and a _memory.continuity block like the template's.`,
    `- _memory.continuity.recent_action and .next_safe_action: EACH <= 96 characters, single line, NO URLs, NO newlines, plainly declarative (avoid the words because / so that / which means / the reason / details / summary).`,
    `- Keep the <!-- SPECKIT_LEVEL: ${item.level} --> and <!-- SPECKIT_TEMPLATE_SOURCE --> and the PHASE PARENT CONTENT DISCIPLINE markers.`,
    ``,
    `## Self-check before finishing`,
    `The folder's children do not exist yet, so a phase-parent validation will still report missing children — that is EXPECTED now; the driver validates after the children land. Just confirm your spec.md frontmatter + anchors are well-formed. Files ONLY inside ${item.folder}. When done, print which file you created.`,
  ].filter(Boolean).join('\n');
}

function buildBrief(item) {
  if (item.kind === 'parent') return buildParentBrief(item);
  const refs = (item.research_refs || []).map((r) => `  - ${r}`).join('\n');
  return [
    `You are a principal engineer authoring ONE spec-kit phase-folder doc set. This is REAL authoring, not a review — you WILL create files. Repo root is the current working directory.`,
    ``,
    `GATE-3 PRE-RESOLVED: your target spec folder is pre-approved — do NOT ask the spec-folder question.`,
    `TARGET FOLDER (create files ONLY here): ${item.folder}`,
    `SCOPE LOCK [HARD]: create/modify files ONLY inside that folder. Touch nothing else in the repo.`,
    ``,
    `## Author these 4 files (Level ${item.level})`,
    `spec.md, plan.md, tasks.md, checklist.md. Do NOT hand-write description.json or graph-metadata.json — deterministic tooling generates those after you finish.`,
    ``,
    `## MIRROR this real example EXACTLY (structural mold)`,
    `Read every file in: ${item.template}`,
    `Copy its structure precisely: the YAML frontmatter shape, the <!-- ANCHOR:name -->…<!-- /ANCHOR:name --> blocks, the <!-- SPECKIT_TEMPLATE_SOURCE --> and <!-- SPECKIT_LEVEL --> and <!-- HVR_REFERENCE --> marker comments, and the section layout of each of its spec.md/plan.md/tasks.md/checklist.md. Replace the example's CONTENT with your phase's content; keep its FORM.`,
    ``,
    `## Read for context`,
    `  - ${path.join(PACKET_ROOT, 'spec.md')}  (the parent program plan — your phase's role, invariants, success criteria)`,
    `  - ${path.join(PACKET_ROOT, 'manifest/phase-tree.json')}  (your phase's outcome + depends_on + siblings)`,
    refs ? `  - Research inputs:\n${refs}` : '',
    ``,
    `## Your phase`,
    `Title: ${item.title}`,
    `Status: ${item.status}`,
    `Outcome: ${item.outcome}`,
    `depends_on: ${JSON.stringify(item.depends_on || [])}`,
    (item.pred_sibling || item.succ_sibling)
      ? `Child adjacency [REQUIRED for phase-parent validation]: add a one-line blockquote directly under the H1 that names ${item.pred_sibling ? 'predecessor `' + item.pred_sibling + '`' : 'predecessor: none (first sibling)'} and ${item.succ_sibling ? 'successor `' + item.succ_sibling + '`' : 'successor: none (last sibling)'}. Write the folder-name slug(s) VERBATIM. These are independent sibling planning contracts — the reference is for navigation/ordering, not a hard runtime dependency.`
      : '',
    ``,
    `Content brief (what this phase must plan to do):`,
    item.content_brief,
    ``,
    `## Spec-kit rules you MUST honor (these are validated)`,
    `- Frontmatter: include title, description, importance_tier (one of low|medium|high|critical), contextType ("planning"), and a _memory.continuity block like the template's.`,
    `- _memory.continuity.recent_action and .next_safe_action: EACH <= 96 characters, single line, NO URLs, NO newlines, plainly declarative (avoid the words because / so that / which means / the reason / details / summary).`,
    `- Keep the <!-- SPECKIT_LEVEL: ${item.level} --> and <!-- SPECKIT_TEMPLATE_SOURCE --> markers from the template.`,
    `- checklist.md: for a Planned phase most items are unchecked "[ ]" (correct — do not fake evidence). Any item you mark "[x]" MUST carry a machine-detectable evidence marker (a backtick-quoted token >=4 chars, or file.ext:line, or a fraction/percent, or a tool keyword like validate.sh).`,
    `- Write dense, specific, phase-appropriate content grounded in the cited files — match the depth of the 017 template, not a stub.`,
    ``,
    `## Self-check before finishing`,
    `Run: bash ${VALIDATE} ${item.folder} --strict`,
    `Fix any reported error EXCEPT ones naming description.json or graph-metadata.json (tooling adds those after you — those are expected to be missing now). Iterate until only those metadata errors remain.`,
    ``,
    `When done, print a one-line summary: which files you created and the final validate tail. Remember: files ONLY inside ${item.folder}.`,
  ].filter(Boolean).join('\n');
}

// ---------- dispatch one agent (async, with executor fallback) ----------
// A folder is authored when its doc set exists (leaf = the 4 md files; parent = spec.md only).
function folderAuthored(item) {
  const abs = path.join(ROOT, item.folder);
  if (!fs.existsSync(path.join(abs, 'spec.md'))) return false;
  if (item.kind === 'parent') return true;
  return ['plan.md', 'tasks.md', 'checklist.md'].every((f) => fs.existsSync(path.join(abs, f)));
}

function runExecutor(item, exec, logFd) {
  return new Promise((resolve) => {
    const brief = buildBrief(item);
    let cmd, args, env;
    if (exec.kind === 'codex') {
      cmd = 'codex';
      args = ['exec', '-m', exec.model, '-c', 'model_reasoning_effort=' + exec.effort,
        '-c', 'service_tier=fast', '-c', 'approval_policy=never', '--sandbox', 'workspace-write', brief];
      env = { ...process.env, AI_SESSION_CHILD: '1' };
    } else {
      cmd = 'opencode';
      args = ['run', '--model', exec.model, '--variant', exec.variant, '--format', 'json', '--dir', ROOT, brief];
      // 'ignore' stdin = /dev/null (opencode hangs without closed stdin); MK_SPEC_GATE_ENFORCE=0
      // stops the child inheriting an enforced spec-gate; AI_SESSION_CHILD=1 shares the worktree.
      env = { ...process.env, AI_SESSION_CHILD: '1', MK_SPEC_GATE_ENFORCE: '0' };
    }
    const t0 = Date.now();
    const child = spawn(cmd, args, { cwd: ROOT, stdio: ['ignore', logFd, logFd], env });
    const timer = setTimeout(() => { try { child.kill('SIGKILL'); } catch {} }, TIMEOUT_MS);
    child.on('close', (code) => { clearTimeout(timer); resolve({ kind: exec.kind, code, ms: Date.now() - t0 }); });
    child.on('error', (e) => { clearTimeout(timer); resolve({ kind: exec.kind, code: -1, err: String(e && e.message), ms: Date.now() - t0 }); });
  });
}

// Try each executor in EXECUTOR_CHAIN until the folder is authored, so a codex error/kill
// falls through to opencode without losing the folder.
async function dispatchOne(item) {
  fs.mkdirSync(LOGDIR, { recursive: true });
  fs.mkdirSync(path.join(ROOT, item.folder), { recursive: true });
  const log = path.join(LOGDIR, `author-${item.id}.log`);
  const out = fs.openSync(log, 'w');
  const attempts = [];
  let totalMs = 0, lastCode = -1;
  for (let i = 0; i < EXECUTOR_CHAIN.length; i++) {
    const r = await runExecutor(item, EXECUTOR_CHAIN[i], out);
    attempts.push(EXECUTOR_CHAIN[i].kind + ':' + r.code);
    totalMs += r.ms; lastCode = r.code;
    if (r.code === 0 && folderAuthored(item)) break;
    if (i < EXECUTOR_CHAIN.length - 1) {
      fs.writeSync(out, `\n\n===== ${EXECUTOR_CHAIN[i].kind} did not author the folder (code=${r.code}); falling back to ${EXECUTOR_CHAIN[i + 1].kind} =====\n\n`);
    }
  }
  try { fs.closeSync(out); } catch {}
  return { id: item.id, folder: item.folder, code: folderAuthored(item) ? 0 : lastCode, ms: totalMs, attempts, log };
}

// ---------- deterministic post-processing (metadata + validate) ----------
function sh(cmd, args) {
  const r = spawnSync(cmd, args, { cwd: ROOT, encoding: 'utf8', timeout: 180 * 1000, maxBuffer: 32 * 1024 * 1024 });
  return { status: r.status, out: (r.stdout || '') + (r.stderr || '') };
}
function postProcess(item) {
  const abs = path.join(ROOT, item.folder);
  const steps = {};
  // generate-description.js requires TWO positionals: <folder-path> <base-path>.
  // base-path is the repo root against which the folder's canonical identity is resolved.
  steps.gen_desc = sh('node', [GEN_DESC, abs, ROOT, '--level', String(item.level)]).status;
  // Re-derive the graph-metadata fingerprint AFTER description.json exists so the
  // source-doc set is complete when the integrity hash is computed.
  steps.backfill = sh('node', [BACKFILL, abs]).status;
  const v = sh('bash', [VALIDATE, item.folder, '--strict']);
  const tail = v.out.split('\n').filter((l) => /Errors:|Warnings:|RESULT:|Summary:/.test(l)).join(' | ');
  steps.validate_status = v.status;
  steps.validate_tail = tail;
  // Exit 0 = fully clean under --strict (no errors AND no warnings, across the folder
  // and — for a parent — its recursed children). A loose /PASSED/ match would
  // false-positive on a child's PASSED line while the parent itself FAILED on a warning.
  steps.pass = (v.status === 0);
  return steps;
}

// ---------- concurrency pool ----------
async function pool(items, n, fn) {
  const results = [];
  let i = 0;
  const workers = Array.from({ length: Math.min(n, items.length) }, async () => {
    while (i < items.length) {
      const idx = i++;
      results[idx] = await fn(items[idx]);
    }
  });
  await Promise.all(workers);
  return results;
}

// ---------- main ----------
async function main() {
  const argv = process.argv.slice(2);
  const wave = parseInt((argv[argv.indexOf('--wave') + 1] || '1'), 10);
  const concurrency = parseInt((argv[argv.indexOf('--concurrency') + 1] || '2'), 10);
  const dryRun = argv.includes('--dry-run');
  const executorMode = argv.indexOf('--executor') >= 0 ? argv[argv.indexOf('--executor') + 1] : 'fallback';
  const onlyArg = argv.indexOf('--only') >= 0 ? argv[argv.indexOf('--only') + 1] : null;
  const onlyIds = onlyArg ? new Set(onlyArg.split(',').map((s) => s.trim())) : null;
  EXECUTOR_CHAIN = executorMode === 'codex' ? [CODEX]
    : executorMode === 'opencode' ? [OPENCODE]
    : [CODEX, OPENCODE]; // fallback (default): codex first, opencode when codex errors out

  const wl = loadJSON(WORKLIST, null);
  if (!wl || !Array.isArray(wl.items)) { console.error('FATAL: bad worklist'); process.exit(2); }
  let items = wl.items.filter((x) => x.wave === wave && !x.done);
  // --only narrows both dispatch AND post-process to the named ids, so re-authoring a
  // single failed folder never rewrites its already-validated siblings' metadata.
  if (onlyIds) items = items.filter((x) => onlyIds.has(String(x.id)));
  if (!items.length) { console.error(`No pending items for wave ${wave}${onlyIds ? ` matching --only ${onlyArg}` : ''}`); process.exit(2); }

  console.log(`Swarm wave ${wave}: ${items.length} folders, concurrency ${concurrency}, executor chain [${EXECUTOR_CHAIN.map((e) => e.kind).join(' -> ')}]`);
  if (dryRun) {
    for (const it of items) { console.log(`\n===== ${it.id} (${it.folder}) =====\n`); console.log(buildBrief(it).slice(0, 1400) + '\n…[truncated]'); }
    return;
  }

  // Resume support: skip re-dispatching already-authored folders (folderAuthored) after an
  // interrupted run, but still post-process every wave item below.
  const toAuthor = items.filter((it) => !folderAuthored(it));
  const already = items.filter(folderAuthored);
  if (already.length) console.log(`Resume: ${already.length} already-authored, skipping re-dispatch: ${already.map((x) => x.id).join(', ')}`);

  console.log(`[${nowStamp()}] dispatching ${toAuthor.length} agents…`);
  const dispatched = toAuthor.length ? await pool(toAuthor, concurrency, dispatchOne) : [];
  console.log(`[${nowStamp()}] agents returned; post-processing ${items.length} folders (metadata + validate)…`);

  // Post-process leaves before parents: a phase-parent only validates AS a parent
  // once ≥1 child folder exists, and backfill derives children_ids from present children.
  const ordered = [...items].sort((a, b) => (a.kind === 'parent' ? 1 : 0) - (b.kind === 'parent' ? 1 : 0));
  for (const item of ordered) {
    const d = dispatched.find((x) => x.id === item.id) || { code: 'skip', ms: 0, attempts: ['skip'] };
    const post = postProcess(item);
    const row = { id: item.id, folder: item.folder, agent_code: d.code, agent_attempts: d.attempts || [], agent_ms: d.ms, ...post, ts: nowStamp() };
    fs.appendFileSync(RESULTS, JSON.stringify(row) + '\n');
    console.log(`  ${item.id}: [${(d.attempts || ['skip']).join(',')}] (${Math.round(d.ms / 1000)}s) | validate: ${post.validate_tail || '(none)'} | PASS=${post.pass}`);
  }
  console.log(`\nWave ${wave} done. Results: ${RESULTS} | logs: ${LOGDIR}`);
}

main();
