// ───────────────────────────────────────────────────────────────
// MODULE: Vector Index
// ───────────────────────────────────────────────────────────────
// Feature catalog: Hybrid search pipeline
// Backward-compatible export surface across split modules.

export {
  MAX_TRIGGERS_PER_MEMORY,
  to_embedding_buffer,
  parse_trigger_phrases,
  get_error_message,
  get_error_code,
} from './vector-index-types.js';
export type {
  MemoryIndexRow,
  IndexMemoryParams,
  UpdateMemoryParams,
  VectorSearchOptions,
  EnrichedSearchResult,
} from './vector-index-types.js';
export {
  SCHEMA_VERSION,
  run_migrations,
  ensure_schema_version,
  migrate_confidence_columns,
  ensure_canonical_file_path_support,
  migrate_constitutional_tier,
  create_common_indexes,
  ensureCompanionTables,
  create_schema,
  ensureSchemaVersion,
  runMigrations,
  createSchema,
  createCommonIndexes,
  migrateConfidenceColumns,
  ensureCanonicalFilePathSupport,
  migrateConstitutionalTier,
} from './vector-index-schema.js';
export {
  index_memory,
  index_memory_deferred,
  update_memory,
  delete_memory,
  delete_memory_by_path,
  delete_memories,
  update_embedding_status,
  update_confidence,
  indexMemory,
  indexMemoryDeferred,
  updateMemory,
  deleteMemory,
  deleteMemoryByPath,
  deleteMemories,
  updateEmbeddingStatus,
  updateConfidence,
} from './vector-index-mutations.js';
export {
  get_memory,
  get_memories_by_folder,
  get_memory_count,
  get_status_counts,
  get_stats,
  vector_search,
  get_constitutional_memories_public,
  multi_concept_search,
  extract_title,
  extract_snippet,
  extract_tags,
  extract_date,
  generate_query_embedding,
  keyword_search,
  vector_search_enriched,
  multi_concept_search_enriched,
  multi_concept_keyword_search,
  parse_quoted_terms,
  apply_smart_ranking,
  apply_diversity,
  get_related_memories,
  get_usage_stats,
  find_cleanup_candidates,
  get_memory_preview,
  verify_integrity,
  getMemory,
  getMemoriesByFolder,
  getMemoryCount,
  getStatusCounts,
  getStats,
  vectorSearch,
  getConstitutionalMemories,
  multiConceptSearch,
  extractTitle,
  extractSnippet,
  extractTags,
  extractDate,
  generateQueryEmbedding,
  keywordSearch,
  vectorSearchEnriched,
  multiConceptSearchEnriched,
  multiConceptKeywordSearch,
  parseQuotedTerms,
  applySmartRanking,
  applyDiversity,
  getRelatedMemories,
  getUsageStats,
  findCleanupCandidates,
  getMemoryPreview,
  verifyIntegrity,
} from './vector-index-queries.js';
export {
  LRUCache,
  get_query_cache,
  get_cache_key,
  cached_search,
  clear_search_cache,
  learn_from_selection,
  link_related_on_save,
  record_access,
  enhanced_search,
  cachedSearch,
  clearSearchCache,
  learnFromSelection,
  linkRelatedOnSave,
  recordAccess,
  enhancedSearch,
  getCacheKey,
} from './vector-index-aliases.js';

// Re-export store items that aren't re-exported by other modules
export {
  initializeDb,
  initialize_db,
  closeDb,
  close_db,
  getDb,
  get_db,
  getDbPath,
  get_db_path,
  clearConstitutionalCache,
  validateFilePath,
  isVectorSearchAvailable,
  SQLiteVectorStore,
  getConfirmedEmbeddingDimension,
  getEmbeddingDim,
  validateEmbeddingDimension,
  EMBEDDING_DIM,
  DEFAULT_DB_PATH,
  search_weights,
  safe_read_file_async,
  safe_parse_json,
  validate_file_path_local,
  get_embedding_dim,
  get_confirmed_embedding_dimension,
  validate_embedding_dimension,
  is_vector_search_available,
  clear_constitutional_cache,
  get_constitutional_memories,
  init_prepared_statements,
  clear_prepared_statements,
  refresh_interference_scores_for_folder,
  sqlite_vec_available,
} from './vector-index-store.js';

// Snake_case aliases for store exports used by legacy callers
export {
  isVectorSearchAvailable as is_vector_search_available_alias,
} from './vector-index-store.js';
